<?php
function ensureOpeningBalanceTables(PDO $pdo): void {
    $pdo->exec("CREATE TABLE IF NOT EXISTS journal_entries (id VARCHAR(64) PRIMARY KEY,entry_date DATE NOT NULL,entry_number VARCHAR(60) NOT NULL UNIQUE,description VARCHAR(500) NOT NULL,branch_id VARCHAR(64) NULL,source_type VARCHAR(30) NOT NULL DEFAULT 'manual',source_id VARCHAR(64) NULL,posted TINYINT(1) NOT NULL DEFAULT 1,status VARCHAR(20) NOT NULL DEFAULT 'Posted',created_by VARCHAR(64) NULL,posted_by VARCHAR(64) NULL,posted_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)");
    $pdo->exec("CREATE TABLE IF NOT EXISTS journal_lines (id VARCHAR(64) PRIMARY KEY,journal_id VARCHAR(64) NOT NULL,account_id VARCHAR(64) NOT NULL,debit DECIMAL(18,2) NOT NULL DEFAULT 0,credit DECIMAL(18,2) NOT NULL DEFAULT 0,memo VARCHAR(500) NULL,INDEX(journal_id),INDEX(account_id))");
    $pdo->exec("CREATE TABLE IF NOT EXISTS journal_postings (id VARCHAR(64) PRIMARY KEY,journal_id VARCHAR(64) NOT NULL,source_type VARCHAR(40) NOT NULL,source_id VARCHAR(64) NULL,posting_key VARCHAR(60) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'Posted',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_posting(source_type,source_id,posting_key))");
}
ensureOpeningBalanceTables($pdo);
if ($method !== 'POST') respondError('Method not allowed',405);
$user=requireAuthenticatedUser($pdo);requireAuthenticatedUserPermission($pdo,$user,'settings:edit');$d=getInput();
$date=trim((string)($d['date']??''));$branchId=trim((string)($d['branchId']??''));$lines=$d['lines']??[];
if(!preg_match('/^\d{4}-\d{2}-\d{2}$/D',$date)||!is_array($lines)||count($lines)<2)respondError('Tanggal dan minimal dua akun saldo awal wajib diisi',422);
if($branchId!=='')requireAccessibleBranch($pdo,$user,$branchId);
$clean=[];$debit=0.0;$credit=0.0;foreach($lines as $line){$accountId=trim((string)($line['accountId']??''));$dr=round((float)($line['debit']??0),2);$cr=round((float)($line['credit']??0),2);if($accountId===''||($dr>0&&$cr>0)||($dr<=0&&$cr<=0))respondError('Setiap saldo awal harus memiliki satu akun dan debit atau kredit',422);$clean[]=[$accountId,$dr,$cr];$debit+=$dr;$credit+=$cr;}
if(round($debit,2)!==round($credit,2)||$debit<=0)respondError('Total saldo awal debit dan kredit harus seimbang',422);
$ids=array_values(array_unique(array_column(array_map(fn($x)=>['id'=>$x[0]],$clean),'id')));$marks=implode(',',array_fill(0,count($ids),'?'));$q=$pdo->prepare("SELECT COUNT(*) FROM chart_of_accounts WHERE is_active=1 AND id IN ($marks)");$q->execute($ids);if((int)$q->fetchColumn()!==count($ids))respondError('Ada akun saldo awal yang tidak ditemukan atau nonaktif',422);
$pdo->beginTransaction();try{$key='OPENING-'.$date.'-'.($branchId?:'GENERAL');$exists=$pdo->prepare('SELECT journal_id FROM journal_postings WHERE source_type=? AND posting_key=? LIMIT 1');$exists->execute(['opening_balance',$key]);if($exists->fetchColumn())respondError('Saldo awal untuk tanggal dan cabang tersebut sudah pernah dibuat',409);$id=generateId();$number='OB-'.$date;$pdo->prepare("INSERT INTO journal_entries(id,entry_date,entry_number,description,branch_id,source_type,source_id,posted,status,created_by,posted_by,posted_at) VALUES(?,?,?,?,?,?,?,1,'Posted',?,?,NOW())")->execute([$id,$date,$number,'Saldo awal '.$date,$branchId?:null,'opening_balance',$key,$user['id']??null,$user['id']??null]);$insert=$pdo->prepare('INSERT INTO journal_lines(id,journal_id,account_id,debit,credit,memo) VALUES(?,?,?,?,?,?)');foreach($clean as [$account,$dr,$cr])$insert->execute([generateId(),$id,$account,$dr,$cr,'Saldo awal '.$date]);$pdo->prepare("INSERT INTO journal_postings(id,journal_id,source_type,source_id,posting_key,status) VALUES(?,?,?,?,?,'Posted')")->execute([generateId(),$id,'opening_balance',$key,$key]);$pdo->commit();respondSuccess(['id'=>$id,'number'=>$number],'Saldo awal berhasil diposting');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
