<?php
$pdo->exec("CREATE TABLE IF NOT EXISTS warehouse_transfers(
 id VARCHAR(64) PRIMARY KEY,transfer_number VARCHAR(40) NOT NULL UNIQUE,transfer_date DATE NOT NULL,
 source_warehouse_id VARCHAR(20) NOT NULL,destination_warehouse_id VARCHAR(20) NOT NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'Draft',delivery_method VARCHAR(40) NULL,notes VARCHAR(500) NULL,
 sent_by_id VARCHAR(64) NULL,sent_by_name VARCHAR(150) NULL,sent_at DATETIME NULL,
 received_by_id VARCHAR(64) NULL,received_by_name VARCHAR(150) NULL,received_at DATETIME NULL,
 created_by VARCHAR(64) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_transfer_status(status),INDEX idx_transfer_destination(destination_warehouse_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS warehouse_transfer_items(
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,transfer_id VARCHAR(64) NOT NULL,item_id VARCHAR(64) NOT NULL,
 item_code VARCHAR(40) NOT NULL,item_name VARCHAR(255) NOT NULL,category_name VARCHAR(150) NULL,unit VARCHAR(30) NOT NULL,
 qty_sent INT NOT NULL,qty_received INT NOT NULL DEFAULT 0,
 UNIQUE KEY uq_transfer_item(transfer_id,item_id),INDEX idx_transfer_item(transfer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

$actor=$requestUser??requireAuthenticatedUser($pdo);
$allowed=array_fill_keys(getAccessibleBranchIds($pdo,$actor),true);
$mapTransfer=function(array $row)use($pdo){
 $stmt=$pdo->prepare("SELECT id,item_id AS itemId,item_code AS itemCode,item_name AS itemName,category_name AS categoryName,unit,qty_sent AS qtySent,qty_received AS qtyReceived FROM warehouse_transfer_items WHERE transfer_id=? ORDER BY id");$stmt->execute([$row['id']]);
 return ['id'=>$row['id'],'transferNumber'=>$row['transfer_number'],'date'=>$row['transfer_date'],'sourceWarehouseId'=>$row['source_warehouse_id'],'sourceWarehouseName'=>$row['source_name'],'sourceBranchId'=>$row['source_branch_id'],'sourceBranchName'=>$row['source_branch_name'],'destinationWarehouseId'=>$row['destination_warehouse_id'],'destinationWarehouseName'=>$row['destination_name'],'destinationBranchId'=>$row['destination_branch_id'],'destinationBranchName'=>$row['destination_branch_name'],'status'=>$row['status'],'deliveryMethod'=>$row['delivery_method']??'','notes'=>$row['notes']??'','sentById'=>$row['sent_by_id'],'sentByName'=>$row['sent_by_name'],'sentAt'=>$row['sent_at'],'receivedById'=>$row['received_by_id'],'receivedByName'=>$row['received_by_name'],'receivedAt'=>$row['received_at'],'items'=>$stmt->fetchAll()];
};
if($method==='GET'){
 $rows=$pdo->query("SELECT t.*,sw.name source_name,sw.branch_id source_branch_id,sb.name source_branch_name,dw.name destination_name,dw.branch_id destination_branch_id,db.name destination_branch_name FROM warehouse_transfers t JOIN warehouses sw ON sw.id=t.source_warehouse_id JOIN branches sb ON sb.id=sw.branch_id JOIN warehouses dw ON dw.id=t.destination_warehouse_id JOIN branches db ON db.id=dw.branch_id ORDER BY t.transfer_date DESC,t.created_at DESC")->fetchAll();
 $out=[];foreach($rows as $row)if(isset($allowed[$row['source_branch_id']])||isset($allowed[$row['destination_branch_id']]))$out[]=$mapTransfer($row);$warehouseOptions=$pdo->query("SELECT w.id,w.code,w.name,w.branch_id AS branchId,b.name AS branchName,w.is_default AS isDefault FROM warehouses w JOIN branches b ON b.id=w.branch_id WHERE w.is_active=1 AND w.is_system=0 AND b.is_active=1 ORDER BY b.name,w.name")->fetchAll();respondSuccess(['transfers'=>$out,'warehouses'=>$warehouseOptions]);
}
if($method==='POST'){
 $d=getInput();$source=(string)($d['sourceWarehouseId']??'');$destination=(string)($d['destinationWarehouseId']??'');$date=(string)($d['date']??date('Y-m-d'));$status=($d['action']??'send')==='draft'?'Draft':'Dalam Perjalanan';
 if(!$source||!$destination||$source===$destination||empty($d['items']))respondError('Gudang asal, tujuan, dan rincian barang wajib diisi',422);
 $wh=$pdo->prepare("SELECT w.id,w.code warehouse_code,w.branch_id,b.code branch_code,b.name branch_name FROM warehouses w JOIN branches b ON b.id=w.branch_id WHERE w.id IN (?,?) AND w.is_active=1");$wh->execute([$source,$destination]);$whMap=[];foreach($wh->fetchAll()as$row)$whMap[$row['id']]=$row;if(count($whMap)!==2)respondError('Gudang tidak valid',422);requireAccessibleBranch($pdo,$actor,$whMap[$source]['branch_id']);
 $sourceLetter=substr(preg_replace('/[^A-Z0-9]/','',strtoupper(preg_replace('/^CABANG\s+/i','',$whMap[$source]['branch_name']))),0,1);$destinationLetter=substr(preg_replace('/[^A-Z0-9]/','',strtoupper(preg_replace('/^CABANG\s+/i','',$whMap[$destination]['branch_name']))),0,1);$prefix='TRF-'.$sourceLetter.'-'.$destinationLetter.'-'.date('ymd',strtotime($date)).'-';
 $senderId=(string)($d['sentById']??$actor['id']);$userStmt=$pdo->prepare("SELECT id,name,is_active FROM users WHERE id=?");$userStmt->execute([$senderId]);$sender=$userStmt->fetch();if(!$sender||!(bool)$sender['is_active']||!in_array($whMap[$source]['branch_id'],getUserBranchIds($pdo,$senderId),true))respondError('Petugas pengirim tidak valid untuk gudang asal',422);
 $pdo->beginTransaction();try{
  $last=$pdo->prepare("SELECT transfer_number FROM warehouse_transfers WHERE transfer_number LIKE ? ORDER BY transfer_number DESC LIMIT 1 FOR UPDATE");$last->execute([$prefix.'%']);$lastNo=(string)$last->fetchColumn();$number=$prefix.str_pad((string)($lastNo?(int)substr($lastNo,-4)+1:1),4,'0',STR_PAD_LEFT);$id='WTR-'.bin2hex(random_bytes(12));
  $pdo->prepare("INSERT INTO warehouse_transfers(id,transfer_number,transfer_date,source_warehouse_id,destination_warehouse_id,status,delivery_method,notes,sent_by_id,sent_by_name,sent_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)")->execute([$id,$number,$date,$source,$destination,$status,$d['deliveryMethod']??'',$d['notes']??'',$status==='Dalam Perjalanan'?$sender['id']:null,$status==='Dalam Perjalanan'?$sender['name']:null,$status==='Dalam Perjalanan'?date('Y-m-d H:i:s'):null,$actor['id']]);
  $itemStmt=$pdo->prepare("SELECT id,code,name,category_name,unit,type,is_active FROM items WHERE id=?");$stockStmt=$pdo->prepare("SELECT quantity FROM warehouse_stocks WHERE warehouse_id=? AND item_id=? FOR UPDATE");$insert=$pdo->prepare("INSERT INTO warehouse_transfer_items(transfer_id,item_id,item_code,item_name,category_name,unit,qty_sent) VALUES(?,?,?,?,?,?,?)");
  foreach($d['items']as$line){$qty=(int)($line['qty']??0);$itemStmt->execute([$line['itemId']??'']);$item=$itemStmt->fetch();if(!$item||$item['type']!=='Persediaan'||!$item['is_active']||$qty<=0)throw new InvalidArgumentException('Rincian barang tidak valid');$stockStmt->execute([$source,$item['id']]);$available=(int)($stockStmt->fetchColumn()?:0);if($status==='Dalam Perjalanan'&&$available<$qty)throw new InvalidArgumentException("Stok {$item['name']} tidak cukup ({$available})");$insert->execute([$id,$item['id'],$item['code'],$item['name'],$item['category_name'],$item['unit'],$qty]);if($status==='Dalam Perjalanan'){adjustWarehouseStockAllowNegative($pdo,$source,$whMap[$source]['branch_id'],$item['id'],-$qty);$mid='MOV-'.date('ymdHis').'-'.bin2hex(random_bytes(3));$pdo->prepare("INSERT INTO stock_movements(id,item_id,source_warehouse_id,destination_warehouse_id,quantity,movement_type,notes,created_by) VALUES(?,?,?,?,?,'transfer_send',?,?)")->execute([$mid,$item['id'],$source,$destination,$qty,'Kirim '.$number,$actor['id']]);}}
  $pdo->commit();respondSuccess(['id'=>$id,'transferNumber'=>$number],'Transfer barang disimpan');
 }catch(Exception$e){if($pdo->inTransaction())$pdo->rollBack();respondError($e->getMessage(),422);}
}
if($method==='PUT'&&$id){
 $d=getInput();if(($d['action']??'')!=='receive')respondError('Aksi tidak valid',422);$pdo->beginTransaction();try{
  $header=$pdo->prepare("SELECT t.*,dw.branch_id destination_branch_id FROM warehouse_transfers t JOIN warehouses dw ON dw.id=t.destination_warehouse_id WHERE t.id=? FOR UPDATE");$header->execute([$id]);$transfer=$header->fetch();if(!$transfer||!in_array($transfer['status'],['Dalam Perjalanan','Diterima Sebagian'],true))throw new InvalidArgumentException('Pengiriman tidak ditemukan atau sudah selesai');requireAccessibleBranch($pdo,$actor,$transfer['destination_branch_id']);
  $receiverId=(string)($d['receivedById']??$actor['id']);$userStmt=$pdo->prepare("SELECT id,name,is_active FROM users WHERE id=?");$userStmt->execute([$receiverId]);$receiver=$userStmt->fetch();if(!$receiver||!(bool)$receiver['is_active']||!in_array($transfer['destination_branch_id'],getUserBranchIds($pdo,$receiverId),true))throw new InvalidArgumentException('Petugas penerima tidak valid untuk gudang tujuan');
  $lines=[];foreach(($d['items']??[])as$line)$lines[(string)($line['itemId']??'')]=(int)($line['qtyReceived']??0);if(!$lines)throw new InvalidArgumentException('Pilih minimal satu barang yang diterima');
  $items=$pdo->prepare("SELECT * FROM warehouse_transfer_items WHERE transfer_id=? FOR UPDATE");$items->execute([$id]);$receivedAny=false;foreach($items->fetchAll()as$item){$qty=$lines[$item['item_id']]??0;$remaining=(int)$item['qty_sent']-(int)$item['qty_received'];if($qty<0||$qty>$remaining)throw new InvalidArgumentException("Jumlah terima {$item['item_name']} melebihi sisa kiriman");if($qty>0){$receivedAny=true;$pdo->prepare("UPDATE warehouse_transfer_items SET qty_received=qty_received+? WHERE id=?")->execute([$qty,$item['id']]);adjustWarehouseStockAllowNegative($pdo,$transfer['destination_warehouse_id'],$transfer['destination_branch_id'],$item['item_id'],$qty);$mid='MOV-'.date('ymdHis').'-'.bin2hex(random_bytes(3));$pdo->prepare("INSERT INTO stock_movements(id,item_id,source_warehouse_id,destination_warehouse_id,quantity,movement_type,notes,created_by) VALUES(?,?,?,?,?,'transfer_receive',?,?)")->execute([$mid,$item['item_id'],$transfer['source_warehouse_id'],$transfer['destination_warehouse_id'],$qty,'Terima '.$transfer['transfer_number'],$actor['id']]);}}
  if(!$receivedAny)throw new InvalidArgumentException('Jumlah diterima harus lebih dari nol');$sum=$pdo->prepare("SELECT SUM(qty_sent) sent,SUM(qty_received) received FROM warehouse_transfer_items WHERE transfer_id=?");$sum->execute([$id]);$tot=$sum->fetch();$newStatus=(int)$tot['received']>=(int)$tot['sent']?'Diterima':'Diterima Sebagian';$pdo->prepare("UPDATE warehouse_transfers SET status=?,received_by_id=?,received_by_name=?,received_at=NOW() WHERE id=?")->execute([$newStatus,$receiver['id'],$receiver['name'],$id]);$pdo->commit();respondSuccess(null,'Penerimaan transfer disimpan');
 }catch(Exception$e){if($pdo->inTransaction())$pdo->rollBack();respondError($e->getMessage(),422);}
}
respondError('Method not allowed',405);
