import { useEffect, useMemo, useState } from 'react';
import { Download, RefreshCw, Search } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../lib/apiClient';
import IndonesianDateInput from '../components/IndonesianDateInput';

type Payment={id:string;paymentNumber:string;date:string;amount:number;paymentMethod:string;accountId?:string;accountName?:string;branchId:string;customerName:string;invoiceNumber:string};
type Account={id:string;name:string;accountType:string;branchId?:string;balance:number;unsubmitted:number;isActive:boolean};
type Deposit={id:string;depositNumber:string;date:string;branchId:string;branchName:string;sourceName:string;destinationName:string;amount:number;status:string};
type Summary={branchId:string;unsubmitted:number};
type Movement={id:string;date:string;branchId:string;number:string;description:string;account:string;kind:'Masuk'|'Keluar'|'Transfer';amount:number};
const money=(v:number)=>`Rp ${Number(v||0).toLocaleString('id-ID')}`;
const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const csv=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;

export default function CashBankReport(){
  const {data,currentBranchId}=useApp();const now=new Date();
  const [payments,setPayments]=useState<Payment[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[deposits,setDeposits]=useState<Deposit[]>([]),[summaries,setSummaries]=useState<Summary[]>([]),[loading,setLoading]=useState(false);
  const [from,setFrom]=useState(localDate(new Date(now.getFullYear(),now.getMonth(),1))),[to,setTo]=useState(localDate(now)),[kind,setKind]=useState('ALL'),[search,setSearch]=useState('');
  const load=async()=>{setLoading(true);const[p,a,d]=await Promise.all([api.get('customer-payments'),api.get('cash-accounts'),api.get('branch-deposits')]);if(p.success)setPayments(p.data||[]);if(a.success)setAccounts(a.data||[]);if(d.success){setDeposits(d.data?.deposits||[]);setSummaries(d.data?.summary||[])}setLoading(false)};
  useEffect(()=>{void load()},[]);
  const movements=useMemo<Movement[]>(()=>{
    const incoming=payments.map(p=>({id:`in-${p.id}`,date:p.date,branchId:p.branchId,number:p.paymentNumber,description:`Pembayaran ${p.invoiceNumber} - ${p.customerName}`,account:p.accountName||p.paymentMethod,kind:'Masuk' as const,amount:Number(p.amount||0)}));
    const outgoing=data.purchaseInvoices.flatMap(inv=>(inv.payments||[]).map(p=>({id:`out-${inv.id}-${p.id}`,date:p.date,branchId:inv.branchId,number:p.paymentNumber,description:`Pembayaran supplier ${inv.supplierName} - ${inv.invoiceNumber}`,account:accounts.find(account=>account.id===p.bankAccount)?.name||p.bankAccount||p.paymentMethod,kind:'Keluar' as const,amount:Number(p.amount||0)})));
    const transfers=deposits.map(d=>({id:`dep-${d.id}`,date:d.date,branchId:d.branchId,number:d.depositNumber,description:`Setoran ${d.branchName} (${d.status})`,account:`${d.sourceName} → ${d.destinationName}`,kind:'Transfer' as const,amount:Number(d.amount||0)}));
    return [...incoming,...outgoing,...transfers].filter(r=>(currentBranchId==='ALL'||r.branchId===currentBranchId)&&(!from||r.date>=from)&&(!to||r.date<=to)&&(kind==='ALL'||r.kind===kind)&&`${r.number} ${r.description} ${r.account}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)||b.number.localeCompare(a.number));
  },[payments,accounts,deposits,data.purchaseInvoices,currentBranchId,from,to,kind,search]);
  const cashIn=movements.filter(r=>r.kind==='Masuk').reduce((s,r)=>s+r.amount,0),cashOut=movements.filter(r=>r.kind==='Keluar').reduce((s,r)=>s+r.amount,0),balance=accounts.filter(a=>a.isActive&&(!a.branchId||currentBranchId==='ALL'||a.branchId===currentBranchId)).reduce((s,a)=>s+Number(a.balance||0),0),unsubmitted=summaries.filter(s=>currentBranchId==='ALL'||s.branchId===currentBranchId).reduce((n,s)=>n+Number(s.unsubmitted||0),0);
  const exportCsv=()=>{const h=['Tanggal','Nomor','Jenis','Keterangan','Akun','Masuk','Keluar'];const b=movements.map(r=>[r.date,r.number,r.kind,r.description,r.account,r.kind==='Masuk'?r.amount:0,r.kind==='Keluar'?r.amount:0].map(csv).join(','));const blob=new Blob(['\uFEFF'+[h.map(csv).join(','),...b].join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`laporan_kas_bank_${from}_${to}.csv`;a.click();URL.revokeObjectURL(url)};
  return <div className="space-y-3 pb-4">
    <div className="flex justify-end gap-2"><button onClick={()=>void load()} className="h-9 rounded-lg border px-3 text-blue-700"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button><button onClick={exportCsv} disabled={!movements.length} className="inline-flex h-9 items-center gap-2 rounded-lg border border-green-300 px-3 text-sm font-semibold text-green-700 disabled:opacity-40"><Download className="h-4 w-4"/>Export CSV</button></div>
    <div className="grid grid-cols-2 gap-2 lg:grid-cols-4"><Card label="Saldo Kas & Bank" value={money(balance)} note={`${accounts.filter(a=>a.isActive).length} akun aktif`}/><Card label="Kas Masuk" value={money(cashIn)} note="pembayaran pelanggan"/><Card label="Kas Keluar" value={money(cashOut)} note="pembayaran supplier"/><Card label="Tunai Belum Disetor" value={money(unsubmitted)} note="per posisi saat ini"/></div>
    <div className="flex flex-wrap gap-2 border-b border-blue-200 pb-2"><label className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari nomor, pelanggan, supplier, akun..." className="h-9 w-full rounded-lg border pl-9 pr-3 text-sm"/></label><select value={kind} onChange={e=>setKind(e.target.value)} className="h-9 rounded-lg border px-3 text-sm"><option value="ALL">Semua Transaksi</option><option>Masuk</option><option>Keluar</option><option>Transfer</option></select><IndonesianDateInput value={from} onChange={setFrom} className="h-9 w-36 text-sm"/><IndonesianDateInput value={to} onChange={setTo} className="h-9 w-36 text-sm"/></div>
    <div className="overflow-hidden rounded-xl border bg-white"><div className="max-h-[calc(100vh-330px)] overflow-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="sticky top-0 bg-blue-900 text-left text-xs uppercase text-white"><tr>{['Tanggal / Nomor','Jenis','Keterangan','Akun','Masuk','Keluar'].map(x=><th key={x} className="px-3 py-2.5">{x}</th>)}</tr></thead><tbody className="divide-y">{movements.map(r=><tr key={r.id} className="hover:bg-blue-50/40"><td className="px-3 py-2"><b className="text-blue-700">{r.number}</b><small className="block text-gray-500">{r.date}</small></td><td className="px-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${r.kind==='Masuk'?'bg-green-100 text-green-700':r.kind==='Keluar'?'bg-red-100 text-red-700':'bg-blue-100 text-blue-700'}`}>{r.kind}</span></td><td className="px-3">{r.description}</td><td className="px-3">{r.account}</td><td className="px-3 text-right font-semibold text-green-700">{r.kind==='Masuk'?money(r.amount):'-'}</td><td className="px-3 text-right font-semibold text-red-600">{r.kind==='Keluar'?money(r.amount):'-'}</td></tr>)}</tbody></table></div>{!movements.length&&<div className="p-12 text-center text-gray-400">Tidak ada mutasi sesuai filter.</div>}<div className="flex justify-end gap-5 border-t bg-gray-50 px-4 py-2 text-sm"><span>Masuk <b className="text-green-700">{money(cashIn)}</b></span><span>Keluar <b className="text-red-600">{money(cashOut)}</b></span><span>Bersih <b>{money(cashIn-cashOut)}</b></span></div></div>
  </div>;
}
function Card({label,value,note}:{label:string;value:string;note:string}){return <div className="rounded-xl border bg-white p-3 shadow-sm"><p className="text-xs text-gray-500">{label}</p><p className="truncate text-lg font-bold text-gray-900">{value}</p><p className="text-[11px] text-gray-400">{note}</p></div>}
