import {useState,useEffect} from 'react';
import {List,Plus,RefreshCw,Search,Filter,Download,Upload,Printer,Settings,ChevronDown,Save,Trash2,X,Lightbulb,ArrowUpDown} from 'lucide-react';
import './ChartOfAccounts.css';
import {api} from '../lib/apiClient';
import {useApp} from '../context/AppContext';

const types=['Kas & Bank','Piutang Usaha','Persediaan','Aset Lancar Lainnya','Aset Tetap','Akumulasi Penyusutan','Aset Lainnya','Utang Usaha','Liabilitas Jangka Pendek','Liabilitas Jangka Panjang','Modal','Pendapatan','Beban Pokok Penjualan','Beban','Beban Lainnya','Pendapatan Lainnya'];
type Account={revision?:number;accountType?:string;normalBalance?:string;id:string;code:string;name:string;type:string;parent:string;balance:string;date:string;notes:string;inactive:boolean};
const empty=():Account=>({id:'',code:'',name:'',type:types[0],parent:'',balance:'',date:'2025-01-01',notes:'',inactive:false});
const generic:Record<string,string>={Asset:'Aset (umum)',Liability:'Liabilitas (umum)',Equity:'Modal (umum)',Revenue:'Pendapatan (umum)',Expense:'Beban (umum)'};
const group=(t:string)=>['Kas & Bank','Piutang Usaha','Persediaan','Aset Lancar Lainnya','Aset Tetap','Akumulasi Penyusutan','Aset Lainnya',generic.Asset].includes(t)?'Asset':['Utang Usaha','Liabilitas Jangka Pendek','Liabilitas Jangka Panjang',generic.Liability].includes(t)?'Liability':['Modal',generic.Equity].includes(t)?'Equity':['Pendapatan','Pendapatan Lainnya',generic.Revenue].includes(t)?'Revenue':'Expense';
const mapAccount=(a:any):Account=>({...empty(),id:a.id,code:a.code,name:a.name,type:a.detailType||generic[a.accountType]||a.accountType,parent:a.parentId||'',inactive:!a.isActive,notes:a.notes||'',revision:a.revision,accountType:a.accountType,normalBalance:a.normalBalance});
export default function ChartOfAccounts(){
 const {hasPermission}=useApp();const canEdit=hasPermission('settings:edit');const [busy,setBusy]=useState(false);
 const load=async()=>{const response=await api.get('chart-of-accounts');if(!response.success)throw new Error(response.message);const rows=(response.data||[]).map(mapAccount);setAccounts(rows);return rows};
 useEffect(()=>{void load().catch(e=>setNotice(e.message))},[]);
 const [accounts,setAccounts]=useState<Account[]>([]);
 const [form,setForm]=useState<Account>(empty),[opened,setOpened]=useState(false),[list,setList]=useState(true),[tab,setTab]=useState('Informasi Umum'),[dirty,setDirty]=useState(false);
 const [sub,setSub]=useState(false),[auto,setAuto]=useState(true),[parentOpen,setParentOpen]=useState(false),[parentSearch,setParentSearch]=useState('');
 const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[active,setActive]=useState('Semua'),[type,setType]=useState('Semua'),[menu,setMenu]=useState(''),[notice,setNotice]=useState(''),[sort,setSort]=useState({key:'code',asc:true}),[allUsers,setAllUsers]=useState(true);
 const [columns,setColumns]=useState(['Kode Perkiraan','Nama','Tipe Akun','Saldo']);
 const [from,setFrom]=useState('2026-09-01'),[to,setTo]=useState('2026-09-10');
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 const update=(value:Partial<Account>)=>{setForm(f=>({...f,...value}));setDirty(true)};
 const close=()=>{if(dirty&&!confirm('Perubahan yang Anda lakukan akan dibatalkan, lanjutkan?'))return;setOpened(false);setList(true);setDirty(false);setParentOpen(false)};
 const open=(a?:Account)=>{if(dirty&&!confirm('Perubahan belum disimpan. Lanjutkan?'))return;setForm(a?{...a}:empty());setSub(!!a?.parent);setAuto(!a);setOpened(true);setList(false);setTab('Informasi Umum');setDirty(false);setNotice('');setParentOpen(false)};
 const descendants=(id:string):string[]=>{const found=new Set<string>([id]);let size=0;while(size!==found.size){size=found.size;accounts.filter(a=>found.has(a.parent)).forEach(a=>found.add(a.id))}return [...found]};

 const parents=accounts.filter(a=>group(a.type)===group(form.type)&&(!form.id||!descendants(form.id).includes(a.id))&&`${a.code} ${a.name}`.toLowerCase().includes(parentSearch.toLowerCase()));
 const ordered: {a:Account;depth:number}[]=[];const seen=new Set<string>();const walk=(parent:string,depth:number)=>accounts.filter(a=>a.parent===parent).sort((a,b)=>{const val=(x:Account)=>sort.key==='name'?x.name:sort.key==='type'?x.type:x.code;return val(a).localeCompare(val(b),'id',{numeric:true})*(sort.asc?1:-1)}).forEach(a=>{if(seen.has(a.id))return;seen.add(a.id);ordered.push({a,depth});walk(a.id,depth+1)});walk('',0);accounts.filter(a=>!seen.has(a.id)).forEach(a=>ordered.push({a,depth:0}));
 const shown=ordered.filter(({a})=>(active==='Semua'||a.inactive===(active==='Ya'))&&(type==='Semua'||a.type===type)&&`${a.code} ${a.name}`.toLowerCase().includes(search.toLowerCase()));
 const save=async()=>{if(busy||!canEdit)return;if(!form.name.trim()||(!(sub&&auto)&&!form.code.trim())||(sub&&!form.parent)){setNotice('Lengkapi kode, nama, dan akun induk.');setTab('Informasi Umum');return}setBusy(true);try{const payload={code:form.code,name:form.name,accountType:group(form.type),detailType:types.includes(form.type)?form.type:'',parentId:sub?form.parent:'',isActive:!form.inactive,notes:form.notes,revision:form.revision,autoCode:sub&&auto&&!form.id,...(form.id?{normalBalance:form.normalBalance}:{})};const r=form.id?await api.update('chart-of-accounts',form.id,payload):await api.create('chart-of-accounts',payload);if(!r.success)throw new Error(r.message);setDirty(false);const savedId=(r.data as {id:string})?.id||form.id;const fresh=await load();const saved=fresh.find((a:Account)=>a.id===savedId);if(saved){setForm(saved);setAuto(false)}setNotice('Akun perkiraan tersimpan.')}catch(e){setNotice(e instanceof Error?e.message:'Gagal menyimpan akun.')}finally{setBusy(false)}};
 const remove=async()=>{if(busy||!canEdit)return;if(!confirm(`Hapus ${form.code} — ${form.name}?`))return;setBusy(true);try{const r=await api.removeWithBody('chart-of-accounts',form.id,{revision:form.revision});if(!r.success)throw new Error(r.message);setDirty(false);setOpened(false);setList(true);await load();setNotice('Akun dihapus.')}catch(e){setNotice(e instanceof Error?e.message:'Gagal menghapus akun.')}finally{setBusy(false)}};
 const exportCsv=()=>{const csv=[['Kode Perkiraan','Nama','Tipe Akun','Saldo'],...shown.map(({a})=>[a.code,a.name,a.type,'Belum tersedia'])].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='akun-perkiraan.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMenu('')};
 return <div className="coa-preview">
 <div className="coa-subbar"><button className={'coa-list-toggle '+(list?'selected':'')} aria-label="Daftar akun" onClick={()=>setList(true)}><List size={23}/></button>{opened&&<div className={'coa-document-tab '+(!list?'selected':'')}><button onClick={()=>setList(false)}>{dirty?'* ':''}{form.id?form.name:'Data Baru'}</button><button aria-label="Tutup Data Baru" disabled={busy} onClick={close}><X size={15}/></button></div>}<button className="coa-help" title="Petunjuk" onClick={()=>setNotice('Gunakan + untuk menambah akun. Klik baris untuk membuka detail. ')}><Lightbulb size={19}/></button></div>
 {notice&&<div className="coa-notice" role="status">{notice}<button aria-label="Tutup pesan" onClick={()=>setNotice('')}><X size={14}/></button></div>}
 {list?<><div className="coa-filters"><label>Non Aktif: <select aria-label="Non Aktif" value={active} onChange={e=>setActive(e.target.value)}>{['Semua','Ya','Tidak'].map(x=><option key={x}>{x}</option>)}</select></label><label>Tipe Akun: <select aria-label="Filter Tipe Akun" value={type} onChange={e=>setType(e.target.value)}>{['Semua',...types,...Object.values(generic)].map(x=><option key={x}>{x}</option>)}</select></label><button className="coa-outline" aria-label="Reset filter" title="Reset filter" onClick={()=>{setActive('Semua');setType('Semua');setQuery('');setSearch('')}}><Filter size={17}/><ChevronDown size={12}/></button></div>
 <div className="coa-toolbar"><button className="coa-primary" aria-label="Tambah akun" title="Tambah" disabled={busy||!canEdit} onClick={()=>open()}><Plus size={26}/></button><button className="coa-outline" aria-label="Muat ulang" title="Muat ulang" onClick={()=>void load().catch(e=>setNotice(e.message))}><RefreshCw size={17}/></button><div className="coa-toolbar-right"><button className="coa-outline" aria-label="Impor akun" title="Impor akun belum tersedia" disabled><Download size={16}/><ChevronDown size={11}/></button><button className="coa-outline" aria-label="Ekspor akun" title="Ekspor CSV" onClick={exportCsv}><Upload size={16}/><ChevronDown size={11}/></button><button className="coa-outline" aria-label="Cetak" title="Cetak daftar akun" onClick={()=>window.print()}><Printer size={16}/></button><div className="coa-menu-anchor"><button className="coa-outline" aria-label="Pengaturan kolom" onClick={()=>setMenu(menu?'':'columns')}><Settings size={16}/><ChevronDown size={11}/></button>{menu==='columns'&&<div className="coa-column-menu">{['Kode Perkiraan','Nama','Tipe Akun','Saldo','Non Aktif','Catatan'].map(c=><label key={c}><input type="checkbox" checked={columns.includes(c)} onChange={e=>setColumns(v=>e.target.checked?[...v,c]:v.length>1?v.filter(x=>x!==c):v)}/>{c}</label>)}</div>}</div><form className="coa-search" onSubmit={e=>{e.preventDefault();setSearch(query)}}><input aria-label="Cari akun" placeholder="Ketik dan [Enter]" value={query} onChange={e=>{setQuery(e.target.value);if(!e.target.value)setSearch('')}}/><button aria-label="Cari"><Search size={18}/></button></form><span className="coa-count">{shown.length}</span></div></div>
 <div className="coa-table-wrap"><table className="coa-table"><thead><tr>{columns.map(c=><th key={c} className={c==='Saldo'?'amount':''}><button onClick={()=>{const key=c==='Nama'?'name':c==='Tipe Akun'?'type':'code';setSort(s=>({key,asc:s.key===key?!s.asc:true}))}}>{c}<ArrowUpDown size={11}/></button></th>)}</tr></thead><tbody>{shown.map(({a,depth})=><tr key={a.id} tabIndex={0} className={a.inactive?'coa-inactive':''} onClick={()=>open(a)} onKeyDown={e=>{if(e.key==='Enter')open(a)}}>{columns.map(c=><td key={c} className={c==='Saldo'?'amount':''} style={c==='Nama'||c==='Kode Perkiraan'?{paddingLeft:10+depth*18}:undefined}>{c==='Kode Perkiraan'?a.code:c==='Nama'?a.name:c==='Tipe Akun'?a.type:c==='Saldo'?'—':c==='Non Aktif'?(a.inactive?'Ya':'Tidak'):a.notes}</td>)}</tr>)}{!shown.length&&<tr><td colSpan={columns.length} className="coa-empty">Belum ada data</td></tr>}</tbody></table></div></>:<div className="coa-editor"><div className="coa-editor-main"><nav className="coa-form-tabs">{['Informasi Umum','Saldo','Lain-lain',...(form.id?['Histori']:[])].map(t=><button key={t} className={(tab===t?'active ':'')+(t==='Histori'?'history':'')} onClick={()=>{setTab(t);setParentOpen(false)}}>{t}</button>)}</nav><section className="coa-form-panel"><fieldset disabled={busy||!canEdit} style={{border:0,padding:0,margin:0,minWidth:0}}>
 {tab==='Informasi Umum'&&<><div className="coa-field"><label htmlFor="coa-type">Tipe Akun</label><select id="coa-type" value={form.type} disabled={!!form.id} onChange={e=>update({type:e.target.value,parent:''})}>{[...types,...(!types.includes(form.type)?[form.type]:[])].map(t=><option key={t}>{t}</option>)}</select></div><div className="coa-field"><label className="coa-check"><input type="checkbox" checked={sub} onChange={e=>{setSub(e.target.checked);setAuto(e.target.checked&&!form.id);update({parent:''})}}/>Sub Akun</label>{sub&&<div className="coa-parent-picker"><div className="coa-input-action"><input aria-label="Akun induk" placeholder="Cari/Pilih..." value={parentOpen?parentSearch:(accounts.find(a=>a.id===form.parent)?`[${accounts.find(a=>a.id===form.parent)!.code}] - ${accounts.find(a=>a.id===form.parent)!.name}`:'')} onFocus={()=>{setParentOpen(true);setParentSearch('')}} onChange={e=>setParentSearch(e.target.value)}/><button aria-label="Cari akun induk" onClick={()=>{setParentOpen(!parentOpen);setParentSearch('')}}><Search size={18}/></button></div>{parentOpen&&<div className="coa-parent-menu">{parents.map(a=><button key={a.id} onClick={()=>{update({parent:a.id});setParentOpen(false)}}><span>{a.name}</span><small>{a.code}</small></button>)}{!parents.length&&<p>Tidak ada akun yang sesuai</p>}</div>}</div>}</div><div className="coa-field"><label htmlFor="coa-code">Kode Perkiraan <b>*</b></label><div>{sub&&!form.id&&<label className="coa-auto"><input type="checkbox" checked={auto} onChange={e=>{setAuto(e.target.checked);setDirty(true)}}/>Pengkodean otomatis dengan prefix kode akun induk</label>}{!(sub&&auto)&&<div className="coa-input-action"><input id="coa-code" aria-label="Kode Perkiraan" value={form.code} onChange={e=>update({code:e.target.value})}/>{form.code&&<button aria-label="Kosongkan kode" onClick={()=>update({code:''})}><X size={14}/></button>}</div>}</div></div><div className="coa-field"><label htmlFor="coa-name">Nama <b>*</b></label><div><div className="coa-input-action"><input id="coa-name" aria-label="Nama akun" value={form.name} onChange={e=>update({name:e.target.value})}/>{form.name&&<button aria-label="Kosongkan nama" onClick={()=>update({name:''})}><X size={14}/></button>}</div><p className="coa-example">Contoh: BCA a/c XXX-XXX, dll</p></div></div></>}
 {tab==='Saldo'&&<><h2>Saldo Awal</h2><p className='coa-access-note'>Saldo awal belum tersedia pada modul ini. Saldo akun tidak ditampilkan sampai terhubung ke buku besar.</p><fieldset disabled><div className="coa-field coa-balance"><label htmlFor="coa-balance">Nilai</label><div className="coa-input-action"><span className="coa-currency">Rp</span><input id="coa-balance" aria-label="Nilai saldo awal" type="number" value={form.balance} onChange={e=>update({balance:e.target.value})}/></div></div><div className="coa-field coa-balance"><label htmlFor="coa-date">per Tgl</label><input id="coa-date" aria-label="Tanggal saldo awal" type="date" value={form.date} onChange={e=>update({date:e.target.value})}/></div></fieldset></>}
 {tab==='Lain-lain'&&<><div className="coa-field coa-wide"><label htmlFor="coa-notes">Catatan</label><textarea id="coa-notes" value={form.notes} onChange={e=>update({notes:e.target.value})}/></div>{form.id&&<div className="coa-field"><label>Non Aktif</label><label className="coa-check"><input type="checkbox" checked={form.inactive} onChange={e=>update({inactive:e.target.checked})}/>Ya</label></div>}{form.id&&form.type==='Kas & Bank'&&<div className="coa-field coa-wide"><label>No. Bukti Kas/Bank</label><input readOnly className="coa-voucher" value={form.name}/></div>}<h2 className="coa-access-title">Akses Pengguna</h2><p className="coa-access-note">Akses mengikuti izin pengaturan akun pengguna. Pembatasan per akun belum tersedia.</p><label className="coa-check"><input type="checkbox" disabled checked={allUsers} onChange={e=>setAllUsers(e.target.checked)}/>Semua Pengguna</label>{!allUsers&&<p className="coa-access-note">Pengaturan akses pengguna belum terhubung dalam pratinjau.</p>}</>}
 {tab==='Histori'&&<><div className="coa-history-filter"><input type="date" aria-label="Histori dari" value={from} onChange={e=>setFrom(e.target.value)}/><span>s/d</span><input type="date" aria-label="Histori sampai" value={to} onChange={e=>setTo(e.target.value)}/><button className="coa-primary" aria-label="Muat histori" onClick={()=>setNotice('Histori transaksi buku besar belum tersedia.')}><RefreshCw size={16}/></button></div><table className="coa-table"><thead><tr>{['Tanggal','No. Sumber #','Tipe Transaksi','Keterangan','Mutasi','Tipe','Saldo'].map(c=><th key={c}>{c}</th>)}</tr></thead><tbody><tr><td colSpan={7} className="coa-empty">Histori buku besar belum tersedia</td></tr></tbody></table></>}
 </fieldset></section></div><aside className="coa-actions"><button className="coa-save" aria-label="Simpan akun" title="Simpan" disabled={!dirty||busy||!canEdit} onClick={()=>void save()}><Save size={33}/></button>{form.id&&<button className="coa-delete" aria-label="Hapus akun" title="Hapus" disabled={busy||!canEdit} onClick={()=>void remove()}><Trash2 size={29}/></button>}</aside></div>}
 </div>
}
