import { useEffect, useMemo, useState } from 'react';
import { Banknote, Plus, RefreshCw, Search, Trash2, X } from 'lucide-react';
import { api } from '../lib/apiClient';
import { useApp } from '../context/AppContext';

type PaymentRow={id:string;paymentNumber:string;invoiceId:string;invoiceNumber:string;date:string;customerName:string;customerId:string;vehicleInfo:string;invoiceTotal:number;invoicePaid:number;amount:number;paymentMethod:string;accountName?:string;branchId:string;createdByName?:string};
type CashAccount={id:string;name:string;accountType:'cash'|'bank'|'qris';branchId?:string};

export default function CustomerPayments(){
 const {data,currentUser,currentBranchId,hasPermission,refreshData}=useApp();
 const [rows,setRows]=useState<PaymentRow[]>([]),[accounts,setAccounts]=useState<CashAccount[]>([]),[loading,setLoading]=useState(false),[search,setSearch]=useState(''),[showForm,setShowForm]=useState(false);
 const today=new Date().toISOString().slice(0,10);
 const [form,setForm]=useState({invoiceId:'',date:today,amount:0,paymentMethod:'Tunai',accountId:'',notes:''});
 const load=async()=>{setLoading(true);const [p,a]=await Promise.all([api.get('customer-payments'),api.get('cash-accounts')]);if(p.success)setRows(p.data||[]);else window.alert(p.message);if(a.success)setAccounts(a.data||[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const unpaid=data.invoices.filter(i=>i.total>i.payment&&(currentBranchId==='ALL'||i.branchId===currentBranchId));
 const invoice=data.invoices.find(i=>i.id===form.invoiceId),outstanding=invoice?Math.max(0,invoice.total-invoice.payment):0;
 const availableAccounts=accounts.filter(a=>form.paymentMethod==='Tunai'?a.accountType==='cash'&&a.branchId===invoice?.branchId:a.accountType!=='cash');
 const filtered=useMemo(()=>rows.filter(r=>(currentBranchId==='ALL'||r.branchId===currentBranchId)&&`${r.paymentNumber} ${r.invoiceNumber} ${r.customerName} ${r.vehicleInfo}`.toLowerCase().includes(search.toLowerCase())),[rows,search,currentBranchId]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!invoice||!form.accountId||form.amount<=0||form.amount>outstanding)return window.alert('Periksa invoice, akun tujuan, dan nominal.');const r=await api.create('customer-payments',{...form,createdBy:currentUser?.id,createdByName:currentUser?.name});if(!r.success)return window.alert(r.message);await refreshData();await load();setShowForm(false);setForm({invoiceId:'',date:today,amount:0,paymentMethod:'Tunai',accountId:'',notes:''})};
 const remove=async(r:PaymentRow)=>{if(!window.confirm(`Hapus ${r.paymentNumber}?`))return;const x=await api.remove('customer-payments',r.id);if(!x.success)return window.alert(x.message);await refreshData();await load()};
 return <div className="space-y-3"><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari pembayaran, invoice, pelanggan..." className="w-full rounded-lg border py-2.5 pl-9 pr-3"/></div><button onClick={()=>void load()} className="rounded-lg border p-2.5 text-blue-700"><RefreshCw className={`h-5 w-5 ${loading?'animate-spin':''}`}/></button>{hasPermission('invoice:edit')&&<button onClick={()=>setShowForm(true)} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 text-white"><Plus className="h-4 w-4"/>Pembayaran</button>}</div>
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-blue-900 text-white"><tr>{['Tanggal','No. Pembayaran','Invoice','Pelanggan','Total','Dibayar','Sisa','Masuk Ke','Input','Aksi'].map(x=><th key={x} className="px-3 py-3 text-left text-xs uppercase">{x}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(r=><tr key={r.id}><td className="px-3 py-3">{r.date}</td><td className="px-3 font-semibold text-blue-700">{r.paymentNumber}</td><td className="px-3">{r.invoiceNumber}</td><td className="px-3"><b>{r.customerName}</b><small className="block text-gray-500">{r.vehicleInfo}</small></td><td className="px-3">Rp {r.invoiceTotal.toLocaleString('id-ID')}</td><td className="px-3 font-semibold text-green-700">Rp {r.amount.toLocaleString('id-ID')}</td><td className="px-3">Rp {Math.max(0,r.invoiceTotal-r.invoicePaid).toLocaleString('id-ID')}</td><td className="px-3"><b>{r.accountName||'-'}</b><small className="block text-gray-500">{r.paymentMethod}</small></td><td className="px-3">{r.createdByName||'-'}</td><td className="px-3">{hasPermission('invoice:edit')&&<button onClick={()=>void remove(r)} className="p-2 text-red-600"><Trash2 className="h-4 w-4"/></button>}</td></tr>)}{!filtered.length&&<tr><td colSpan={10} className="p-12 text-center text-gray-400">Belum ada pembayaran</td></tr>}</tbody></table></div>
 {showForm&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={save} className="w-full max-w-lg rounded-xl bg-white"><header className="flex justify-between border-b p-4"><b className="flex gap-2"><Banknote/>Pembayaran Pelanggan</b><button type="button" onClick={()=>setShowForm(false)}><X/></button></header><div className="space-y-4 p-5"><label className="block text-sm">Invoice<select required value={form.invoiceId} onChange={e=>{const i=data.invoices.find(x=>x.id===e.target.value);setForm({...form,invoiceId:e.target.value,amount:i?i.total-i.payment:0,accountId:''})}} className="mt-1 w-full rounded-lg border p-2.5"><option value="">Pilih invoice</option>{unpaid.map(i=><option key={i.id} value={i.id}>{i.invoiceNumber} · {i.customerName} · Rp {(i.total-i.payment).toLocaleString('id-ID')}</option>)}</select></label>{invoice&&<div className="grid grid-cols-3 rounded-lg bg-blue-50 p-3 text-sm"><span>Total<br/><b>Rp {invoice.total.toLocaleString('id-ID')}</b></span><span>Dibayar<br/><b>Rp {invoice.payment.toLocaleString('id-ID')}</b></span><span>Sisa<br/><b className="text-red-600">Rp {outstanding.toLocaleString('id-ID')}</b></span></div>}<div className="grid grid-cols-2 gap-3"><label className="text-sm">Tanggal<input type="date" min={invoice?.date} max={today} value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="text-sm">Metode<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value,accountId:''})} className="mt-1 w-full rounded-lg border p-2.5"><option>Tunai</option><option>Transfer</option><option>QRIS</option></select></label></div><label className="block text-sm">Diterima ke<select required value={form.accountId} onChange={e=>setForm({...form,accountId:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5"><option value="">Pilih Kas/Bank tujuan</option>{availableAccounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="block text-sm">Nominal<input type="number" min="1" max={outstanding} value={form.amount||''} onChange={e=>setForm({...form,amount:Number(e.target.value)})} className="mt-1 w-full rounded-lg border p-2.5 text-lg font-bold"/></label><label className="block text-sm">Catatan<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="mt-1 w-full rounded-lg border p-2.5"/></label></div><footer className="flex justify-end gap-2 border-t p-4"><button type="button" onClick={()=>setShowForm(false)} className="rounded-lg border px-4 py-2">Batal</button><button className="rounded-lg bg-blue-600 px-4 py-2 text-white">Simpan</button></footer></form></div>}</div>;
}
