import { FileText, List, Package, Trash2, X } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { useApp } from '../context/AppContext';

const statusTone:Record<string,string>={Draft:'bg-slate-100 text-slate-700',Diterima:'bg-green-100 text-green-700',Difakturkan:'bg-blue-100 text-blue-700',Sebagian:'bg-amber-100 text-amber-700',Batal:'bg-red-100 text-red-700'};

export default function GoodsReceiptDetail(){
 const{id=''}=useParams();const navigate=useNavigate();const{data,hasPermission,receiveGoods,deleteGoodsReceipt}=useApp();const receipt=data.goodsReceipts.find(row=>row.id===id);
 if(!receipt)return <div className="rounded-xl border bg-white p-12 text-center"><Package className="mx-auto mb-3 h-12 w-12 text-slate-300"/><p className="text-slate-500">Penerimaan tidak ditemukan atau belum selesai dimuat.</p><button onClick={()=>navigate('/receipts')} className="mt-4 rounded bg-blue-600 px-4 py-2 text-white">Kembali</button></div>;
 const branch=data.branches.find(row=>row.id===receipt.branchId),warehouse=data.warehouses.find(row=>row.id===receipt.warehouseId);
 const remove=async()=>{if(!confirm(`Hapus penerimaan ${receipt.receiptNumber}?`))return;await deleteGoodsReceipt(receipt.id);navigate('/receipts')};
 const accept=async()=>{if(!confirm(`Terima barang ${receipt.receiptNumber}? Stok akan ditambahkan.`))return;await receiveGoods(receipt.id)};
 return <div className="min-h-[calc(100vh-150px)] overflow-hidden rounded-none border-0 bg-[#f2f2f2] shadow-none [&_thead]:!bg-[#60778e]">
  <div className="flex items-end border-b border-[#b8b8b8] bg-[#ededed]"><button onClick={()=>navigate('/receipts')} title="Daftar Penerimaan" className="flex h-11 w-14 items-center justify-center rounded-t border border-b-0 border-[#a9a9a9] bg-[#c8c8c8] text-[#4b4b4b]"><List className="h-5 w-5"/></button><div className="ml-1 flex h-11 items-center gap-3 rounded-t border border-b-0 border-[#b8b8b8] border-t-2 border-t-blue-600 bg-[#f2f2f2] px-4 font-mono font-semibold text-blue-700">{receipt.receiptNumber}<button onClick={()=>navigate('/receipts')} title="Tutup"><X className="h-4 w-4"/></button></div></div>
  <div className="grid gap-3 bg-[#ededed] p-5 text-sm sm:grid-cols-2 lg:grid-cols-4"><Info label="Tanggal" value={new Date(`${receipt.date}T00:00:00`).toLocaleDateString('id-ID')}/><Info label="Status" value={receipt.status} badge={statusTone[receipt.status]}/><Info label="No Terima" value={receipt.doNumber||'-'}/><Info label="Pemasok" value={receipt.supplierName||'Supplier belum ditentukan'}/><Info label="Cabang" value={branch?.name||'-'}/><Info label="Gudang" value={warehouse?.name||'-'}/><Info label="Diterima Oleh" value={receipt.receivedBy||'-'}/><Info label="Pengiriman" value={receipt.deliveryMethod||'-'}/></div>
  <div className="p-4"><div className="mb-2 flex items-center justify-between"><h3 className="flex items-center gap-2 font-semibold"><Package className="h-5 w-5 text-blue-600"/>Rincian Barang</h3><span>{receipt.items.length} barang</span></div><div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[720px] text-sm"><thead className="bg-slate-600 text-white"><tr><th className="rounded-tl-lg p-3 text-left">Kode #</th><th className="p-3 text-left">Nama Barang</th><th className="p-3 text-center">Kuantitas</th><th className="p-3 text-center">Satuan</th><th className="p-3 text-center">Difakturkan</th><th className="rounded-tr-lg p-3 text-center">Sisa</th></tr></thead><tbody>{receipt.items.map(item=><tr key={item.id} className="border-t"><td className="p-3 font-mono">{item.itemCode}</td><td className="p-3">{item.itemName}</td><td className="p-3 text-center">{item.qty}</td><td className="p-3 text-center">{item.unit}</td><td className="p-3 text-center">{item.qtyInvoiced||0}</td><td className="p-3 text-center">{item.qty-(item.qtyInvoiced||0)}</td></tr>)}</tbody></table></div>{(receipt.notes||receipt.shippingNotes)&&<div className="mt-3 rounded border bg-slate-50 p-3 text-sm"><b>Keterangan</b><p className="text-slate-600">{receipt.notes||receipt.shippingNotes}</p></div>}
   <div className="mt-5 flex flex-wrap justify-end gap-2 border-t pt-4">{receipt.status==='Draft'&&hasPermission('receipt:edit')&&<button onClick={accept} className="rounded bg-green-600 px-4 py-2 font-medium text-white">Terima Barang</button>}{receipt.status==='Diterima'&&receipt.sourceType!=='Transfer Gudang'&&hasPermission('purchase:view')&&<button onClick={()=>navigate('/purchase-invoices')} className="flex items-center gap-2 rounded bg-blue-600 px-4 py-2 font-medium text-white"><FileText className="h-4 w-4"/>Faktur Pembelian</button>}{hasPermission('receipt:delete')&&<button onClick={remove} className="flex items-center gap-2 rounded border border-red-300 px-4 py-2 text-red-700"><Trash2 className="h-4 w-4"/>Hapus</button>}<button onClick={()=>navigate('/receipts')} className="rounded border px-4 py-2">Tutup</button></div>
  </div>
 </div>
}
function Info({label,value,badge}:{label:string;value:string;badge?:string}){return <div><span className="text-slate-500">{label}</span>{badge?<div><span className={`mt-1 inline-block rounded-full px-2 py-0.5 text-xs font-medium ${badge}`}>{value}</span></div>:<b className="block text-slate-900">{value}</b>}</div>}
