import { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronDown, FileText, Lightbulb, List, MoreHorizontal, Package, Paperclip, Save, Search, Settings, Trash2, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import type { GoodsReceiptItem } from '../types';
import { localDateKey } from '../lib/date';
import { api } from '../lib/apiClient';
import { vehicleBrands as fallbackVehicleBrandNames, vehicleModels as fallbackVehicleModels } from '../lib/vehicleCatalog';
import ItemSearchOption from '../components/ItemSearchOption';

const deliveryOptions=['Diantar Langsung','Grab','Gojek','Ekspedisi','Diambil Sendiri','Lainnya'];

type ReceiptEntryForm = {
 date:string;doNumber:string;warehouseId:string;supplierId:string;deliveryMethod:string;
 deliveryOther:string;shippingNotes:string;notes:string;receivedById:string;items:GoodsReceiptItem[];
};

type QuickCatalogGeneration = { id:string;name:string;isActive:boolean;engineCcs:number[] };
type QuickCatalogModel = { id:string;name:string;isActive:boolean;generations:QuickCatalogGeneration[] };
type QuickCatalogBrand = { id:string;name:string;isActive:boolean;models:QuickCatalogModel[] };
type QuickItemBrand = { id:string;code:string;name:string;isActive:boolean;usageCount?:number };
type QuickItemForm = { name:string;barcode:string;categoryId:string;itemBrandId:string;unit:string;vehicleBrandId:string;modelId:string;generationId:string;engineCc:number };

const blankQuickItem:QuickItemForm={name:'',barcode:'',categoryId:'',itemBrandId:'',unit:'PCS',vehicleBrandId:'',modelId:'',generationId:'',engineCc:0};
const fallbackQuickCatalog:QuickCatalogBrand[]=[
 {id:'UNIVERSAL',name:'Universal / Semua Mobil',isActive:true,models:[]},
 ...fallbackVehicleBrandNames.filter(name=>name!=='Lainnya').map(name=>({id:name,name,isActive:true,models:(fallbackVehicleModels[name]||[]).map(model=>({id:`${name}:${model}`,name:model,isActive:true,generations:[]}))})),
];

export default function GoodsReceiptEntry(){
 const navigate=useNavigate();
 const{data,currentUser,currentBranchId,generateReceiptNumber,addGoodsReceipt,addItem}=useApp();
 const branchId=(currentBranchId==='ALL'?currentUser?.branchId:currentBranchId)||'BR-001';
 const warehouses=data.warehouses.filter(w=>w.branchId===branchId&&w.isActive&&!w.isSystem);const defaultWarehouse=warehouses.find(w=>w.isDefault)||warehouses[0];
 const draftKey=`goods-receipt-draft:${currentUser?.id||currentUser?.username||'user'}:${branchId}`;
 const[form,setForm]=useState<ReceiptEntryForm>(()=>{const blank:ReceiptEntryForm={date:localDateKey(),doNumber:'',warehouseId:defaultWarehouse?.id||'',supplierId:'',deliveryMethod:'Diantar Langsung',deliveryOther:'',shippingNotes:'',notes:'',receivedById:currentUser?.id||'',items:[]};try{const saved=localStorage.getItem(draftKey);const restored:ReceiptEntryForm=saved?{...blank,...JSON.parse(saved)}:blank;return restored.deliveryMethod==='Diantar Supplier'?{...restored,deliveryMethod:'Diantar Langsung'}:restored}catch{return blank}});
 useEffect(()=>{try{localStorage.setItem(draftKey,JSON.stringify(form))}catch{/* penyimpanan draft tidak tersedia */}},[draftKey,form]);
 const closeEntry=()=>{localStorage.removeItem(draftKey);navigate('/receipts')};
 const[search,setSearch]=useState('');const[showPicker,setShowPicker]=useState(false);const[showQuick,setShowQuick]=useState(false);const[saving,setSaving]=useState(false);const[selectedLineId,setSelectedLineId]=useState('');const[detailTab,setDetailTab]=useState<'detail'|'info'>('detail');const[quick,setQuick]=useState<QuickItemForm>(blankQuickItem);const[quickSaving,setQuickSaving]=useState(false);const[quickError,setQuickError]=useState('');const[catalogBrands,setCatalogBrands]=useState<QuickCatalogBrand[]>(fallbackQuickCatalog);const[itemBrands,setItemBrands]=useState<QuickItemBrand[]>([]);const[openRailMenu,setOpenRailMenu]=useState<'document'|'more'|''>('');const attachmentRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{let active=true;void api.get<{brands:QuickCatalogBrand[]}>('vehicle-catalog').then(response=>{if(active&&response.success&&response.data?.brands?.length)setCatalogBrands(response.data.brands)});return()=>{active=false}},[]);
 useEffect(()=>{let active=true;void api.get<QuickItemBrand[]>('item-brands').then(response=>{if(active)setItemBrands((response.data||[]).filter(brand=>brand.isActive))});return()=>{active=false}},[]);
 const[columnWidths,setColumnWidths]=useState<number[]>(()=>{try{const saved=JSON.parse(localStorage.getItem('receipt-entry-column-widths')||'[]');return Array.isArray(saved)&&saved.length===4?saved:[250,620,160,130]}catch{return[250,620,160,130]}});
 const resizeColumn=(index:number,event:React.MouseEvent)=>{event.preventDefault();event.stopPropagation();const startX=event.clientX,startWidth=columnWidths[index];document.body.style.cursor='col-resize';document.body.style.userSelect='none';const move=(mouseEvent:MouseEvent)=>setColumnWidths(current=>{const next=[...current];next[index]=Math.max(index===1?220:90,startWidth+mouseEvent.clientX-startX);return next});const stop=()=>{document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',stop);document.body.style.cursor='';document.body.style.userSelect='';setColumnWidths(current=>{localStorage.setItem('receipt-entry-column-widths',JSON.stringify(current));return current})};document.addEventListener('mousemove',move);document.addEventListener('mouseup',stop)};
 const receiptNumber=generateReceiptNumber(branchId);const receivingUsers=data.users.filter(u=>u.isActive&&(u.branchId===branchId||u.branchIds?.includes(branchId)||u.isOwner));const totalQty=form.items.reduce((sum,line)=>sum+line.qty,0);
 const items=useMemo(()=>{const q=search.toLowerCase();return data.items.filter(i=>i.type==='Persediaan'&&i.isActive&&i.verificationStatus!=='Merged'&&(!q||i.code.toLowerCase().includes(q)||i.name.toLowerCase().includes(q)||(i.barcode||'').toLowerCase().includes(q))).slice(0,30)},[data.items,search]);
 const addLine=(item:typeof data.items[number])=>{const existing=form.items.find(x=>x.itemId===item.id);if(existing){setSelectedLineId(existing.id);setShowPicker(false);return}const lineId=`L-${Date.now()}`;setForm({...form,items:[...form.items,{id:lineId,itemId:item.id,itemCode:item.code,itemName:item.name,qty:1,unit:item.unit,qtyInvoiced:0}]});setSelectedLineId(lineId);setSearch('');setShowPicker(false)};
 const selectedLine=form.items.find(line=>line.id===selectedLineId);const selectedMaster=selectedLine?data.items.find(item=>item.id===selectedLine.itemId):undefined;
 const activeCatalogBrands=catalogBrands.filter(brand=>brand.isActive);const selectedItemBrand=itemBrands.find(brand=>brand.id===quick.itemBrandId);const selectedQuickBrand=activeCatalogBrands.find(brand=>brand.id===quick.vehicleBrandId);const quickModels=(selectedQuickBrand?.models||[]).filter(model=>model.isActive);const selectedQuickModel=quickModels.find(model=>model.id===quick.modelId);const quickGenerations=(selectedQuickModel?.generations||[]).filter(generation=>generation.isActive);const selectedQuickGeneration=quickGenerations.find(generation=>generation.id===quick.generationId);
 const resetQuick=()=>{setQuick(blankQuickItem);setQuickError('');setShowQuick(false)};
 const createQuick=async()=>{setQuickError('');const category=data.itemCategories.find(c=>c.id===quick.categoryId);if(!quick.name.trim()||!category){setQuickError('Nama dan kategori barang wajib diisi.');return}if(!selectedQuickBrand){setQuickError('Pilih minimal satu merek kendaraan atau Universal.');return}const normalizedName=quick.name.trim().toLocaleUpperCase('id-ID');const duplicate=data.items.find(item=>item.verificationStatus!=='Merged'&&item.name.trim().toLocaleUpperCase('id-ID')===normalizedName);if(duplicate){if(window.confirm(`${duplicate.name} sudah ada dengan kode ${duplicate.code}. Pilih barang yang sudah ada?`)){addLine(duplicate);resetQuick()}else setQuickError('Gunakan nama lain jika barang ini memang berbeda.');return}setQuickSaving(true);try{const compatibility={brandId:selectedQuickBrand.id,brandName:selectedQuickBrand.name,modelId:selectedQuickModel?.id,modelName:selectedQuickModel?.name,generationId:selectedQuickGeneration?.id,generationName:selectedQuickGeneration?.name,engineCc:quick.engineCc||null};const item=await addItem({id:`IT-${Date.now()}`,code:'AUTO',name:normalizedName,categoryId:category.id,categoryName:category.name,type:'Persediaan',brand:selectedItemBrand?.name||'',itemBrandId:selectedItemBrand?.id,vehicleBrandId:selectedQuickBrand.id,vehicleBrandName:selectedQuickBrand.name,vehicleBrandIds:[selectedQuickBrand.id],vehicleBrandNames:[selectedQuickBrand.name],vehicleCompatibilities:[compatibility],unit:quick.unit.trim().toUpperCase()||'PCS',stock:0,sellableStock:0,purchasePrice:0,sellingPrice:0,isActive:true,isQuickService:false,description:'Dibuat melalui penerimaan barang',barcode:quick.barcode.trim(),branchId,autoCode:true,provisional:true});addLine(item);resetQuick()}catch(error:any){setQuickError(error?.message||'Barang gagal dibuat. Periksa data lalu coba lagi.')}finally{setQuickSaving(false)}};
 const submit=async(status:'Draft'|'Diterima')=>{const warehouseId=form.warehouseId||defaultWarehouse?.id||'';if(!warehouseId)return alert('Gudang utama cabang aktif belum tersedia.');if(!form.receivedById)return alert('Pilih petugas penerima.');if(!form.items.length)return alert('Tambahkan minimal satu barang.');if(form.deliveryMethod==='Lainnya'&&!form.deliveryOther.trim())return alert('Tuliskan cara pengiriman lainnya.');const receiver=data.users.find(u=>u.id===form.receivedById);setSaving(true);try{await addGoodsReceipt({id:`GR-${Date.now()}`,receiptNumber,date:form.date,supplierId:'',supplierName:'',doNumber:'',sourceType:'Supplier',deliveryMethod:form.deliveryMethod,deliveryOther:form.deliveryOther,shippingNotes:form.shippingNotes,items:form.items,status,notes:form.notes,branchId,warehouseId,receivedBy:receiver?.name||currentUser?.name,receivedById:receiver?.id||currentUser?.id,createdAt:localDateKey()});localStorage.removeItem(draftKey);navigate('/receipts')}catch(e:any){alert(e?.message||'Penerimaan gagal disimpan.')}finally{setSaving(false)}};
 return <div className="goods-receipt-entry relative min-h-[calc(100vh-150px)] overflow-hidden rounded-none border-0 bg-[#f2f2f2] pb-20 shadow-none [&_thead]:!bg-[#60778e]">
 <div className="mt-0.5 flex items-end justify-between border-b border-[#b8b8b8] bg-[#fafafa] pl-1.5 pr-4"><div className="flex items-end"><button onClick={closeEntry} title="Daftar Penerimaan" className="flex h-11 w-14 items-center justify-center rounded-t-lg border border-b-0 border-[#45a90f] bg-[#5bc516] text-white"><List className="h-5 w-5"/></button><div className="ml-1 flex h-11 items-center gap-3 rounded-t-lg border border-b-0 border-[#b8b8b8] bg-[#f2f2f2] px-4 font-mono font-semibold text-blue-700">{receiptNumber}<button onClick={closeEntry}><X className="h-4 w-4"/></button></div></div><div className="mb-1 flex gap-2"><button title="Pengaturan formulir" onClick={()=>alert('Pengaturan tampilan penerimaan barang.')} className="flex h-10 w-10 items-center justify-center rounded border border-blue-500 bg-white text-blue-700"><Settings className="h-5 w-5"/></button><button title="Bantuan" onClick={()=>window.open('/help?article=alur-pembelian','_blank')} className="flex h-10 w-10 items-center justify-center rounded bg-orange-400 text-white"><Lightbulb className="h-5 w-5"/></button></div></div>
  <div className="relative bg-[#ededed] py-3 pl-4 pr-[92px] sm:pl-[66px] sm:pr-[112px]">
   <div className="grid gap-x-10 gap-y-3 text-sm sm:grid-cols-2">
    <label className="min-w-0"><span className="mb-1 block font-medium">Diterima Oleh <span className="text-red-600">*</span></span><select value={form.receivedById} onChange={e=>setForm({...form,receivedById:e.target.value})} className="w-full rounded border border-slate-300 bg-white px-3 py-2">{receivingUsers.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>
    <label className="min-w-0"><span className="mb-1 block font-medium">Tanggal <span className="text-red-600">*</span></span><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="w-full rounded border border-slate-300 bg-white px-3 py-2"/></label>
    <label className="min-w-0"><span className="mb-1 block font-medium">Cara Pengiriman</span><select value={form.deliveryMethod} onChange={e=>setForm({...form,deliveryMethod:e.target.value})} className="w-full rounded border border-slate-300 bg-white px-3 py-2">{deliveryOptions.map(x=><option key={x}>{x}</option>)}</select></label>
    <label className="min-w-0"><span className="mb-1 block font-medium">Gudang Aktif <span className="ml-1 text-emerald-600">●</span></span><select value={form.warehouseId} onChange={e=>setForm({...form,warehouseId:e.target.value})} className="w-full rounded border border-slate-300 bg-white px-3 py-2">{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>
    {form.deliveryMethod==='Lainnya'&&<label className="min-w-0 sm:col-span-2"><span className="mb-1 block font-medium">Pengiriman Lainnya</span><input value={form.deliveryOther} onChange={e=>setForm({...form,deliveryOther:e.target.value})} className="w-full rounded border px-3 py-2"/></label>}
   </div>
   <div className="absolute right-4 top-3 z-20 flex w-[72px] flex-col items-stretch gap-3">
    <button disabled={saving||!form.items.length} onClick={()=>submit('Diterima')} title="Simpan penerimaan" className="flex h-16 items-center justify-center rounded border border-blue-700 bg-[#0874c9] text-white shadow-md disabled:border-gray-300 disabled:bg-gray-200 disabled:text-gray-400"><Save className="h-8 w-8"/><ChevronDown className="h-4 w-4"/></button>
    <div className="relative"><button onClick={()=>setOpenRailMenu(openRailMenu==='document'?'':'document')} title="Dokumen" className="flex h-16 w-full items-center justify-center rounded border border-blue-500 bg-blue-200 text-[#00518b]"><FileText className="h-8 w-8"/><ChevronDown className="h-4 w-4"/></button>{openRailMenu==='document'&&<div className="absolute right-full top-0 z-40 mr-2 w-44 rounded border bg-white py-1 text-sm shadow-xl"><button onClick={()=>window.print()} className="w-full px-3 py-2 text-left hover:bg-blue-50">Cetak formulir</button><button onClick={()=>alert('Faktur pembelian dapat dibuat setelah penerimaan disimpan.')} className="w-full px-3 py-2 text-left hover:bg-blue-50">Buat faktur</button></div>}</div>
    <input ref={attachmentRef} type="file" className="hidden" onChange={event=>event.target.files?.[0]&&alert(`Lampiran dipilih: ${event.target.files[0].name}`)}/><button onClick={()=>attachmentRef.current?.click()} title="Lampiran" className="flex h-16 items-center justify-center rounded border border-blue-500 bg-blue-200 text-[#00518b]"><Paperclip className="h-8 w-8"/><ChevronDown className="h-4 w-4"/></button>
    <div className="relative"><button onClick={()=>setOpenRailMenu(openRailMenu==='more'?'':'more')} title="Pilihan lainnya" className="flex h-16 w-full items-center justify-center rounded border border-green-500 bg-green-300 text-green-800 shadow"><MoreHorizontal className="h-8 w-8"/><ChevronDown className="h-4 w-4"/></button>{openRailMenu==='more'&&<div className="absolute right-full top-0 z-40 mr-2 w-48 rounded border bg-white py-1 text-sm shadow-xl"><button onClick={()=>submit('Draft')} className="w-full px-3 py-2 text-left hover:bg-green-50">Simpan sebagai draft</button><button onClick={()=>setForm(current=>({...current,notes:prompt('Keterangan penerimaan',current.notes)||current.notes}))} className="w-full px-3 py-2 text-left hover:bg-green-50">Isi keterangan</button></div>}</div>
    <button disabled title="Hapus tersedia setelah data disimpan" className="mt-4 flex h-16 items-center justify-center rounded border border-red-300 bg-red-200 text-red-400 disabled:opacity-60"><Trash2 className="h-8 w-8"/></button>
   </div>
  </div>
  <div className="ml-2 mr-[92px] mt-1 overflow-hidden rounded-t-lg border border-slate-300 bg-white">
  <div className="flex flex-wrap items-center justify-between gap-2 border-b bg-white p-2"><div onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setShowPicker(false)}} className="relative w-full max-w-md"><input value={search} onFocus={()=>setShowPicker(true)} onChange={e=>{setSearch(e.target.value);setShowPicker(true)}} placeholder="Cari kode, nama, atau barcode..." className="w-full rounded border px-3 py-2 pr-10 text-sm"/><Search className="pointer-events-none absolute right-3 top-2.5 h-5 w-5"/>{showPicker&&<div className="absolute z-30 mt-1 max-h-64 w-full overflow-auto rounded border bg-white shadow-xl">{items.map(i=><button key={i.id} onClick={()=>addLine(i)} className="block w-full border-b border-slate-200 px-3 py-2 text-left hover:bg-blue-50"><ItemSearchOption name={i.name} code={i.code}/></button>)}<button onClick={()=>{setShowQuick(true);setShowPicker(false)}} className="w-full bg-amber-50 p-2 text-left text-sm font-semibold text-amber-700">+ Barang belum ada</button></div>}</div><div className="flex items-center gap-3"><button onClick={()=>setShowPicker(true)} title="Cari barang" className="flex h-10 w-10 items-center justify-center rounded border border-slate-300 bg-white text-blue-700"><Search className="h-5 w-5"/></button><h3 className="whitespace-nowrap text-base font-medium">{form.items.length} Barang ({totalQty}) <span className="text-red-600">*</span></h3></div></div>
   {showQuick&&<div className="border-b border-amber-200 bg-amber-50 p-3">
    <div className="mb-2 flex items-center justify-between gap-3"><div><h4 className="font-semibold text-amber-950">Buat Barang Baru</h4><p className="text-xs text-amber-800">Barang disimpan sebagai Menunggu Verifikasi dan langsung dipilih.</p></div><button type="button" onClick={resetQuick} disabled={quickSaving} title="Tutup" className="rounded p-1 text-amber-900 hover:bg-amber-100"><X className="h-5 w-5"/></button></div>
    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">
     <label className="lg:col-span-2"><span className="mb-1 block text-xs font-semibold text-slate-600">Nama Barang *</span><input autoFocus value={quick.name} onChange={e=>setQuick({...quick,name:e.target.value})} placeholder="Contoh: EXPANSI WULING CONFERO" className="h-10 w-full rounded border border-slate-300 bg-white px-3 uppercase"/></label>
     <label><span className="mb-1 block text-xs font-semibold text-slate-600">Kode Barcode / Kode Barang Asli <span className="font-normal text-slate-400">(opsional)</span></span><input value={quick.barcode} onChange={e=>setQuick({...quick,barcode:e.target.value})} placeholder="Scan / ketik kode" autoComplete="off" className="h-10 w-full rounded border border-slate-300 bg-white px-3 font-mono"/></label>
     <label><span className="mb-1 block text-xs font-semibold text-slate-600">Kategori *</span><select value={quick.categoryId} onChange={e=>setQuick({...quick,categoryId:e.target.value})} className="h-10 w-full rounded border border-slate-300 bg-white px-3"><option value="">Pilih kategori</option>{data.itemCategories.filter(c=>c.isActive).map(c=><option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}</select></label>
     <label><span className="mb-1 block text-xs font-semibold text-slate-600">Merek Barang</span><select value={quick.itemBrandId} onChange={e=>setQuick({...quick,itemBrandId:e.target.value})} className="h-10 w-full rounded border border-slate-300 bg-white px-3"><option value="">Tanpa merek</option>{itemBrands.map(brand=><option key={brand.id} value={brand.id}>{brand.code} - {brand.name}</option>)}</select></label>
     <label><span className="mb-1 block text-xs font-semibold text-slate-600">Satuan *</span><input value={quick.unit} onChange={e=>setQuick({...quick,unit:e.target.value})} placeholder="PCS" className="h-10 w-full rounded border border-slate-300 bg-white px-3 uppercase"/></label>
     <label><span className="mb-1 block text-xs font-semibold text-slate-600">Merek Mobil *</span><select value={quick.vehicleBrandId} onChange={e=>setQuick({...quick,vehicleBrandId:e.target.value,modelId:'',generationId:'',engineCc:0})} className="h-10 w-full rounded border border-slate-300 bg-white px-3"><option value="">Pilih merek mobil</option>{activeCatalogBrands.map(brand=><option key={brand.id} value={brand.id}>{brand.name}</option>)}</select></label>
     <label><span className="mb-1 block text-xs font-semibold text-slate-600">Model / Tipe</span><select value={quick.modelId} disabled={!selectedQuickBrand||!quickModels.length} onChange={e=>setQuick({...quick,modelId:e.target.value,generationId:'',engineCc:0})} className="h-10 w-full rounded border border-slate-300 bg-white px-3 disabled:bg-slate-100"><option value="">Semua model</option>{quickModels.map(model=><option key={model.id} value={model.id}>{model.name}</option>)}</select></label>
     <label><span className="mb-1 block text-xs font-semibold text-slate-600">Generasi</span><select value={quick.generationId} disabled={!selectedQuickModel||!quickGenerations.length} onChange={e=>setQuick({...quick,generationId:e.target.value,engineCc:0})} className="h-10 w-full rounded border border-slate-300 bg-white px-3 disabled:bg-slate-100"><option value="">Semua generasi</option>{quickGenerations.map(generation=><option key={generation.id} value={generation.id}>{generation.name}</option>)}</select></label>
     <label><span className="mb-1 block text-xs font-semibold text-slate-600">Mesin / CC</span><select value={quick.engineCc} disabled={!selectedQuickGeneration||!selectedQuickGeneration.engineCcs.length} onChange={e=>setQuick({...quick,engineCc:Number(e.target.value)||0})} className="h-10 w-full rounded border border-slate-300 bg-white px-3 disabled:bg-slate-100"><option value={0}>Semua CC</option>{(selectedQuickGeneration?.engineCcs||[]).map(cc=><option key={cc} value={cc}>{(cc/1000).toLocaleString('id-ID',{maximumFractionDigits:1})} L / {cc.toLocaleString('id-ID')} cc</option>)}</select></label>
    </div>
    {quickError&&<div role="alert" className="mt-2 rounded border border-red-200 bg-red-50 px-3 py-2 text-sm font-medium text-red-700">{quickError}</div>}
    <div className="mt-3 flex justify-end gap-2"><button type="button" onClick={resetQuick} disabled={quickSaving} className="rounded border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-600">Batal</button><button type="button" onClick={()=>void createQuick()} disabled={quickSaving} className="min-w-36 rounded bg-amber-500 px-5 py-2 text-sm font-semibold text-white disabled:bg-amber-300">{quickSaving?'Menyimpan...':'Buat & Pilih'}</button></div>
   </div>}
   <div className="min-h-[420px] overflow-x-auto bg-white"><table className="min-w-full table-fixed text-sm" style={{width:columnWidths.reduce((sum,width)=>sum+width,52)}}><colgroup>{columnWidths.map((width,index)=><col key={index} style={{width}}/>)}<col style={{width:52}}/></colgroup><thead className="bg-slate-600 text-white"><tr>{['Kode #','Nama Barang','Kuantitas','Satuan'].map((label,index)=><th key={label} className={`relative p-2 ${index<2?'text-left':'text-center'} ${index===0?'rounded-tl-lg':''}`}>{label}<span onMouseDown={event=>resizeColumn(index,event)} onDoubleClick={()=>{const reset=[250,620,160,130];setColumnWidths(reset);localStorage.setItem('receipt-entry-column-widths',JSON.stringify(reset))}} title="Tarik untuk mengubah lebar kolom" className="absolute -right-1 top-0 z-10 h-full w-2 cursor-col-resize select-none hover:bg-blue-300/60"/></th>)}<th className="rounded-tr-lg border-l border-slate-400 bg-slate-500 p-2"></th></tr></thead><tbody>{form.items.map(line=><tr key={line.id} tabIndex={0} onFocus={()=>setSelectedLineId(line.id)} onClick={()=>setSelectedLineId(line.id)} className={`cursor-pointer border-b outline-none ${selectedLineId===line.id?'bg-slate-200 ring-1 ring-inset ring-blue-400':'hover:bg-slate-50'}`}><td className="truncate p-2 font-mono" title={line.itemCode}>{line.itemCode}</td><td className="truncate p-2" title={line.itemName}>{line.itemName}</td><td className="p-2 text-center">{line.qty}</td><td className="p-2 text-center">{line.unit}</td><td className="border-l border-slate-300 bg-slate-100 p-2 text-center"><button onClick={event=>{event.stopPropagation();setForm({...form,items:form.items.filter(x=>x.id!==line.id)});if(selectedLineId===line.id)setSelectedLineId('')}} title="Hapus barang" className="rounded border border-slate-300 bg-white p-1 text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table>{!form.items.length&&<p className="bg-white py-5 text-center text-slate-500">Belum ada data</p>}</div>
  </div>
  {selectedLine&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/55 p-3" onMouseDown={event=>{if(event.target===event.currentTarget)setSelectedLineId('')}}>
   <div className="flex max-h-[calc(100vh-24px)] w-full max-w-lg flex-col overflow-hidden rounded-lg bg-white shadow-2xl">
    <header className="flex items-center justify-between bg-[#123665] px-5 py-3 text-white"><h2 className="flex items-center gap-3 text-lg font-medium"><Package className="h-5 w-5"/>Rincian Barang</h2><button onClick={()=>setSelectedLineId('')} className="rounded p-1 hover:bg-white/10" title="Tutup"><X className="h-6 w-6"/></button></header>
    <div className="flex border-b px-5 pt-4 text-lg"><button onClick={()=>setDetailTab('detail')} className={`px-4 py-2 ${detailTab==='detail'?'border-b-2 border-red-500 text-red-600':'text-gray-500'}`}>Rincian Barang</button><button onClick={()=>setDetailTab('info')} className={`px-4 py-2 ${detailTab==='info'?'border-b-2 border-red-500 text-red-600':'text-gray-500'}`}>Info lainnya</button></div>
    <div className="min-h-80 overflow-y-auto p-6">
     {detailTab==='detail'?<div className="grid grid-cols-[150px_minmax(0,1fr)] items-center gap-x-5 gap-y-4 text-base">
      <label>Kode #</label><button onClick={()=>navigate(`/items?view=${encodeURIComponent(selectedLine.itemId)}`)} className="w-fit font-mono text-lg font-semibold text-cyan-500 hover:text-cyan-700 hover:underline" title="Buka data barang">{selectedLine.itemCode}</button>
      <label>Nama Barang <span className="text-red-600">*</span></label><input readOnly value={selectedLine.itemName} className="rounded border border-gray-300 bg-white px-3 py-2.5 text-base shadow-sm"/>
      <label>Kuantitas <span className="text-red-600">*</span></label><div className="flex gap-3"><input type="number" min="1" value={selectedLine.qty} onChange={event=>setForm(current=>({...current,items:current.items.map(line=>line.id===selectedLine.id?{...line,qty:Math.max(1,Number(event.target.value)||1)}:line)}))} className="w-40 rounded border border-gray-300 bg-white px-3 py-2.5 text-right"/><div className="rounded border border-gray-300 bg-slate-50 px-4 py-2.5 font-medium">{selectedLine.unit}</div></div>
      <label>Gudang <span className="text-red-600">*</span></label><select value={form.warehouseId} onChange={event=>setForm({...form,warehouseId:event.target.value})} className="rounded border border-gray-300 bg-white px-3 py-2.5">{warehouses.map(warehouse=><option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select>
     </div>:<div className="grid gap-4 sm:grid-cols-2">
      <div className="rounded border bg-slate-50 p-4"><span className="text-sm text-slate-500">Kategori</span><b className="mt-1 block">{selectedMaster?.categoryName||'-'}</b></div>
      <div className="rounded border bg-slate-50 p-4"><span className="text-sm text-slate-500">Merek</span><b className="mt-1 block">{selectedMaster?.brand||'Universal'}</b></div>
      <div className="rounded border bg-slate-50 p-4"><span className="text-sm text-slate-500">Barcode</span><b className="mt-1 block font-mono">{selectedMaster?.barcode||'-'}</b></div>
      <div className="rounded border bg-slate-50 p-4"><span className="text-sm text-slate-500">Stok tercatat</span><b className="mt-1 block">{selectedMaster?.stock??0} {selectedLine.unit}</b></div>
      <div className="rounded border bg-slate-50 p-4 sm:col-span-2"><span className="text-sm text-slate-500">Kecocokan Mobil</span><b className="mt-1 block">{selectedMaster?.vehicleCompatibilities?.length?selectedMaster.vehicleCompatibilities.map(row=>[row.brandName,row.modelName,row.generationName,row.engineCc?`${row.engineCc.toLocaleString('id-ID')} cc`:null].filter(Boolean).join(' · ')).join(', '):(selectedMaster?.vehicleBrandNames?.join(', ')||selectedMaster?.vehicleBrandName||'Universal / Semua Mobil')}</b></div>
     </div>}
    </div>
    <footer className="flex items-center justify-between border-t px-6 py-4"><button onClick={()=>{setForm(current=>({...current,items:current.items.filter(line=>line.id!==selectedLine.id)}));setSelectedLineId('')}} className="rounded border border-blue-600 px-6 py-2.5 text-blue-700 hover:bg-blue-50">Hapus</button><button onClick={()=>setSelectedLineId('')} className="rounded bg-[#174fa3] px-8 py-2.5 text-white hover:bg-blue-800">Lanjut</button></footer>
   </div>
  </div>}
 </div>
}
