import { useMemo, useState } from 'react';
import { ChevronDown, List, MoreHorizontal, Package, Save, Search, Trash2, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import type { GoodsReceipt, GoodsReceiptItem } from '../types';
import { localDateKey } from '../lib/date';

const deliveryOptions=['Diantar Supplier','Grab','Gojek','Ekspedisi','Diambil Sendiri','Lainnya'];

export default function GoodsReceiptEntry(){
 const navigate=useNavigate();
 const{data,currentUser,currentBranchId,generateReceiptNumber,addGoodsReceipt,addItem}=useApp();
 const branchId=(currentBranchId==='ALL'?currentUser?.branchId:currentBranchId)||'BR-001';
 const warehouses=data.warehouses.filter(w=>w.branchId===branchId&&w.isActive&&!w.isSystem);const defaultWarehouse=warehouses.find(w=>w.isDefault)||warehouses[0];
 const[form,setForm]=useState({date:localDateKey(),doNumber:'',warehouseId:defaultWarehouse?.id||'',supplierId:'',deliveryMethod:'Diantar Supplier',deliveryOther:'',shippingNotes:'',notes:'',receivedById:currentUser?.id||'',items:[] as GoodsReceiptItem[]});
 const[search,setSearch]=useState('');const[showPicker,setShowPicker]=useState(false);const[showQuick,setShowQuick]=useState(false);const[saving,setSaving]=useState(false);const[selectedLineId,setSelectedLineId]=useState('');const[quick,setQuick]=useState({name:'',categoryId:'',unit:'PCS',barcode:''});
 const[columnWidths,setColumnWidths]=useState<number[]>(()=>{try{const saved=JSON.parse(localStorage.getItem('receipt-entry-column-widths')||'[]');return Array.isArray(saved)&&saved.length===4?saved:[250,620,160,130]}catch{return[250,620,160,130]}});
 const resizeColumn=(index:number,event:React.MouseEvent)=>{event.preventDefault();event.stopPropagation();const startX=event.clientX,startWidth=columnWidths[index];document.body.style.cursor='col-resize';document.body.style.userSelect='none';const move=(mouseEvent:MouseEvent)=>setColumnWidths(current=>{const next=[...current];next[index]=Math.max(index===1?220:90,startWidth+mouseEvent.clientX-startX);return next});const stop=()=>{document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',stop);document.body.style.cursor='';document.body.style.userSelect='';setColumnWidths(current=>{localStorage.setItem('receipt-entry-column-widths',JSON.stringify(current));return current})};document.addEventListener('mousemove',move);document.addEventListener('mouseup',stop)};
 const receiptNumber=generateReceiptNumber(branchId);const receivingUsers=data.users.filter(u=>u.isActive&&(u.branchId===branchId||u.branchIds?.includes(branchId)||u.isOwner));
 const items=useMemo(()=>{const q=search.toLowerCase();return data.items.filter(i=>i.type==='Persediaan'&&i.isActive&&i.verificationStatus!=='Merged'&&(!q||i.code.toLowerCase().includes(q)||i.name.toLowerCase().includes(q))).slice(0,30)},[data.items,search]);
 const addLine=(item:typeof data.items[number])=>{const existing=form.items.find(x=>x.itemId===item.id);if(existing){setSelectedLineId(existing.id);setShowPicker(false);return}const lineId=`L-${Date.now()}`;setForm({...form,items:[...form.items,{id:lineId,itemId:item.id,itemCode:item.code,itemName:item.name,qty:1,unit:item.unit,qtyInvoiced:0}]});setSelectedLineId(lineId);setSearch('');setShowPicker(false)};
 const selectedLine=form.items.find(line=>line.id===selectedLineId);const selectedMaster=selectedLine?data.items.find(item=>item.id===selectedLine.itemId):undefined;
 const createQuick=async()=>{const category=data.itemCategories.find(c=>c.id===quick.categoryId);if(!quick.name.trim()||!category)return alert('Nama dan kategori barang wajib diisi.');const item=await addItem({id:`IT-${Date.now()}`,code:'AUTO',name:quick.name.toUpperCase(),categoryId:category.id,categoryName:category.name,type:'Persediaan',brand:'',unit:quick.unit||'PCS',stock:0,sellableStock:0,purchasePrice:0,sellingPrice:0,isActive:true,isQuickService:false,description:'Dibuat melalui penerimaan barang',barcode:quick.barcode,branchId,autoCode:true,provisional:true});addLine(item);setShowQuick(false)};
 const submit=async(status:'Draft'|'Diterima')=>{const warehouseId=form.warehouseId||defaultWarehouse?.id||'';if(!warehouseId)return alert('Gudang utama cabang aktif belum tersedia.');if(!form.receivedById)return alert('Pilih petugas penerima.');if(!form.items.length)return alert('Tambahkan minimal satu barang.');if(form.deliveryMethod==='Lainnya'&&!form.deliveryOther.trim())return alert('Tuliskan cara pengiriman lainnya.');const supplier=data.suppliers.find(s=>s.id===form.supplierId),receiver=data.users.find(u=>u.id===form.receivedById);setSaving(true);try{await addGoodsReceipt({id:`GR-${Date.now()}`,receiptNumber,date:form.date,supplierId:supplier?.id||'',supplierName:supplier?.name||'',doNumber:form.doNumber.trim(),sourceType:'Supplier',deliveryMethod:form.deliveryMethod,deliveryOther:form.deliveryOther,shippingNotes:form.shippingNotes,items:form.items,status,notes:form.notes,branchId,warehouseId,receivedBy:receiver?.name||currentUser?.name,receivedById:receiver?.id||currentUser?.id,createdAt:localDateKey()});navigate('/receipts')}catch(e:any){alert(e?.message||'Penerimaan gagal disimpan.')}finally{setSaving(false)}};
 return <div className="goods-receipt-entry relative min-h-[calc(100vh-150px)] overflow-hidden rounded-none border-0 bg-[#f2f2f2] pb-20 shadow-none [&_thead]:!bg-[#60778e]">
  <div className="mt-0.5 flex items-end border-b border-[#b8b8b8] bg-[#fafafa] pl-1.5"><button onClick={()=>navigate('/receipts')} title="Daftar Penerimaan" className="flex h-11 w-14 items-center justify-center rounded-t-lg border border-b-0 border-[#45a90f] bg-[#5bc516] text-white"><List className="h-5 w-5"/></button><div className="ml-1 flex h-11 items-center gap-3 rounded-t-lg border border-b-0 border-[#b8b8b8] bg-[#f2f2f2] px-4 font-medium text-blue-700">Data Baru<button onClick={()=>navigate('/receipts')}><X className="h-4 w-4"/></button></div></div>
  <div className="grid gap-4 bg-[#ededed] px-4 py-3 sm:pl-[66px] sm:pr-6 xl:grid-cols-[minmax(0,440px)_minmax(0,440px)_128px] xl:justify-between">
   <div className="grid grid-cols-[150px_1fr] items-center gap-2 text-sm"><label className="font-medium">Terima dari <span className="text-red-600">*</span></label><select value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})} className="rounded border bg-white px-3 py-2"><option value="">Cari/Pilih Pemasok — boleh menyusul</option>{data.suppliers.filter(s=>s.isActive).map(s=><option key={s.id} value={s.id}>{s.code} - {s.name}</option>)}</select><label className="font-medium">Tanggal <span className="text-red-600">*</span></label><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="rounded border px-3 py-2"/><label className="font-medium">No. Surat Jalan <span className="text-slate-500">(opsional)</span></label><input value={form.doNumber} onChange={e=>setForm({...form,doNumber:e.target.value.toUpperCase()})} placeholder="Nomor surat jalan" className="rounded border bg-white px-3 py-2 font-mono"/></div>
   <div className="grid grid-cols-[150px_1fr] content-start items-center gap-2 text-sm"><label>Gudang</label><select value={form.warehouseId} onChange={e=>setForm({...form,warehouseId:e.target.value})} className="rounded border bg-white px-3 py-2">{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><label>Diterima Oleh</label><select value={form.receivedById} onChange={e=>setForm({...form,receivedById:e.target.value})} className="rounded border bg-white px-3 py-2">{receivingUsers.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><label>Cara Pengiriman</label><select value={form.deliveryMethod} onChange={e=>setForm({...form,deliveryMethod:e.target.value})} className="rounded border bg-white px-3 py-2">{deliveryOptions.map(x=><option key={x}>{x}</option>)}</select>{form.deliveryMethod==='Lainnya'&&<><label>Pengiriman Lainnya</label><input value={form.deliveryOther} onChange={e=>setForm({...form,deliveryOther:e.target.value})} className="rounded border px-3 py-2"/></>}</div>
   <div className="flex flex-col items-center gap-2"><div className="text-center text-xs text-slate-500">No Form #<b className="block font-mono text-blue-700">{receiptNumber}</b></div><button disabled={saving} onClick={()=>submit('Diterima')} className="flex h-14 w-20 items-center justify-center gap-2 rounded bg-blue-700 text-white shadow disabled:opacity-50"><Save className="h-6 w-6"/><ChevronDown className="h-4 w-4"/></button><button title="Pilihan lainnya" className="flex h-10 w-20 items-center justify-center rounded border border-green-500 bg-green-200 text-green-700"><MoreHorizontal/></button></div>
  </div>
  <div className="mx-2 mt-1 rounded border border-slate-300">
   <div className="flex flex-wrap items-center justify-between gap-2 border-b bg-white p-2"><div onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setShowPicker(false)}} className="relative w-full max-w-md"><input value={search} onFocus={()=>setShowPicker(true)} onChange={e=>{setSearch(e.target.value);setShowPicker(true)}} placeholder="Cari/Pilih Barang & Jasa..." className="w-full rounded border px-3 py-2 pr-10 text-sm"/><Search className="pointer-events-none absolute right-3 top-2.5 h-5 w-5"/>{showPicker&&<div className="absolute z-30 mt-1 max-h-64 w-full overflow-auto rounded border bg-white shadow-xl">{items.map(i=><button key={i.id} onClick={()=>addLine(i)} className="flex w-full justify-between border-b px-3 py-2 text-left text-sm hover:bg-blue-50"><span><b>{i.code}</b> · {i.name}</span><span>{i.unit}</span></button>)}<button onClick={()=>{setShowQuick(true);setShowPicker(false)}} className="w-full bg-amber-50 p-2 text-left text-sm font-semibold text-amber-700">+ Barang belum ada</button></div>}</div><h3 className="flex items-center gap-2 text-lg font-semibold"><Package className="h-5 w-5 text-blue-600"/>Rincian Barang <span className="text-red-600">*</span></h3></div>
   {showQuick&&<div className="grid gap-2 border-b bg-amber-50 p-3 sm:grid-cols-4"><input value={quick.name} onChange={e=>setQuick({...quick,name:e.target.value})} placeholder="Nama barang *"/><select value={quick.categoryId} onChange={e=>setQuick({...quick,categoryId:e.target.value})}><option value="">Kategori *</option>{data.itemCategories.filter(c=>c.isActive).map(c=><option key={c.id} value={c.id}>{c.code} - {c.name}</option>)}</select><input value={quick.unit} onChange={e=>setQuick({...quick,unit:e.target.value})}/><button onClick={createQuick} className="rounded bg-amber-500 text-white">Buat & Pilih</button></div>}
   <div className="min-h-[420px] overflow-x-auto"><table className="min-w-full table-fixed text-sm" style={{width:columnWidths.reduce((sum,width)=>sum+width,52)}}><colgroup>{columnWidths.map((width,index)=><col key={index} style={{width}}/>)}<col style={{width:52}}/></colgroup><thead className="bg-slate-600 text-white"><tr>{['Kode #','Nama Barang','Kuantitas','Satuan'].map((label,index)=><th key={label} className={`relative p-2 ${index<2?'text-left':'text-center'} ${index===0?'rounded-tl-lg':''}`}>{label}<span onMouseDown={event=>resizeColumn(index,event)} onDoubleClick={()=>{const reset=[250,620,160,130];setColumnWidths(reset);localStorage.setItem('receipt-entry-column-widths',JSON.stringify(reset))}} title="Tarik untuk mengubah lebar kolom" className="absolute -right-1 top-0 z-10 h-full w-2 cursor-col-resize select-none hover:bg-blue-300/60"/></th>)}<th className="rounded-tr-lg border-l border-slate-400 bg-slate-500 p-2"></th></tr></thead><tbody>{form.items.map(line=><tr key={line.id} tabIndex={0} onFocus={()=>setSelectedLineId(line.id)} onClick={()=>setSelectedLineId(line.id)} className={`cursor-pointer border-b outline-none ${selectedLineId===line.id?'bg-slate-200 ring-1 ring-inset ring-blue-400':'hover:bg-slate-50'}`}><td className="truncate p-2 font-mono" title={line.itemCode}>{line.itemCode}</td><td className="truncate p-2" title={line.itemName}>{line.itemName}</td><td className="p-2 text-center">{line.qty}</td><td className="p-2 text-center">{line.unit}</td><td className="border-l border-slate-300 bg-slate-100 p-2 text-center"><button onClick={event=>{event.stopPropagation();setForm({...form,items:form.items.filter(x=>x.id!==line.id)});if(selectedLineId===line.id)setSelectedLineId('')}} title="Hapus barang" className="rounded border border-slate-300 bg-white p-1 text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table>{!form.items.length&&<p className="py-5 text-center text-slate-500">Belum ada data</p>}{selectedLine&&<div className="m-3 grid gap-2 rounded border border-slate-300 bg-slate-50 p-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-slate-500">Kode</span><b className="block font-mono">{selectedLine.itemCode}</b></div><div><span className="text-slate-500">Nama Barang</span><b className="block">{selectedLine.itemName}</b></div><div><span className="text-slate-500">Kategori</span><b className="block">{selectedMaster?.categoryName||'-'}</b></div><div><span className="text-slate-500">Merek / Stok</span><b className="block">{selectedMaster?.brand||'Universal'} · {selectedMaster?.stock??0} {selectedLine.unit}</b></div></div>}</div>
  </div>
 </div>
}
