import { useEffect, useMemo, useState } from 'react';
import { ChevronDown, FileText, List, MoreHorizontal, Package, Pencil, Save, Search, Trash2, X } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import type { GoodsReceipt, GoodsReceiptItem } from '../types';

const deliveryOptions=['Diantar Supplier','Grab','Gojek','Ekspedisi','Diambil Sendiri','Lainnya'];
const initialWidths=[250,620,160,130];

export default function GoodsReceiptDetail(){
 const{id=''}=useParams();const navigate=useNavigate();const{data}=useApp();const receipt=data.goodsReceipts.find(row=>row.id===id);
 if(!receipt)return <div className="bg-white p-12 text-center"><Package className="mx-auto mb-3 h-12 w-12 text-slate-300"/><p className="text-slate-500">Penerimaan tidak ditemukan atau belum selesai dimuat.</p><button onClick={()=>navigate('/receipts')} className="mt-4 rounded bg-blue-600 px-4 py-2 text-white">Kembali</button></div>;
 return <ReceiptDetailForm receipt={receipt}/>;
}

function ReceiptDetailForm({receipt}:{receipt:GoodsReceipt}){
 const navigate=useNavigate();
 const{data,hasPermission,updateGoodsReceipt,deleteGoodsReceipt,receiveGoods}=useApp();
 const[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[menuOpen,setMenuOpen]=useState(false),[search,setSearch]=useState(''),[showPicker,setShowPicker]=useState(false),[selectedLineId,setSelectedLineId]=useState('');
 const[form,setForm]=useState(()=>toForm(receipt));
 const[columnWidths,setColumnWidths]=useState<number[]>(()=>{try{const saved=JSON.parse(localStorage.getItem('receipt-entry-column-widths')||'[]');return Array.isArray(saved)&&saved.length===4?saved:initialWidths}catch{return initialWidths}});
 useEffect(()=>{if(!editing)setForm(toForm(receipt))},[receipt,editing]);
 const warehouses=data.warehouses.filter(w=>w.branchId===receipt.branchId&&w.isActive&&!w.isSystem);
 const receivingUsers=data.users.filter(u=>u.isActive&&(u.branchId===receipt.branchId||u.branchIds?.includes(receipt.branchId)||u.isOwner));
 const availableItems=useMemo(()=>{const q=search.toLowerCase();return data.items.filter(i=>i.type==='Persediaan'&&i.isActive&&i.verificationStatus!=='Merged'&&(!q||i.code.toLowerCase().includes(q)||i.name.toLowerCase().includes(q))).slice(0,30)},[data.items,search]);
 const selectedLine=form.items.find(line=>line.id===selectedLineId),selectedMaster=selectedLine?data.items.find(item=>item.id===selectedLine.itemId):undefined;
 const addLine=(item:typeof data.items[number])=>{const old=form.items.find(line=>line.itemId===item.id);if(old){setSelectedLineId(old.id);setShowPicker(false);return}const line={id:`L-${Date.now()}`,itemId:item.id,itemCode:item.code,itemName:item.name,qty:1,unit:item.unit,qtyInvoiced:0};setForm(current=>({...current,items:[...current.items,line]}));setSelectedLineId(line.id);setSearch('');setShowPicker(false)};
 const resizeColumn=(index:number,event:React.MouseEvent)=>{event.preventDefault();event.stopPropagation();const startX=event.clientX,startWidth=columnWidths[index];document.body.style.cursor='col-resize';document.body.style.userSelect='none';const move=(mouseEvent:MouseEvent)=>setColumnWidths(current=>{const next=[...current];next[index]=Math.max(index===1?220:90,startWidth+mouseEvent.clientX-startX);return next});const stop=()=>{document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',stop);document.body.style.cursor='';document.body.style.userSelect='';setColumnWidths(current=>{localStorage.setItem('receipt-entry-column-widths',JSON.stringify(current));return current})};document.addEventListener('mousemove',move);document.addEventListener('mouseup',stop)};
 const save=async()=>{if(!form.doNumber.trim())return alert('No Terima wajib diisi.');if(!form.warehouseId||!form.receivedById)return alert('Gudang dan petugas penerima wajib dipilih.');if(!form.items.length)return alert('Tambahkan minimal satu barang.');const supplier=data.suppliers.find(row=>row.id===form.supplierId),receiver=data.users.find(row=>row.id===form.receivedById);setSaving(true);try{await updateGoodsReceipt(receipt.id,{...receipt,...form,supplierName:supplier?.name||'',receivedBy:receiver?.name||receipt.receivedBy});setEditing(false);alert('Penerimaan berhasil diperbarui.')}catch(error:any){alert(error?.message||'Gagal memperbarui penerimaan.')}finally{setSaving(false)}};
 const remove=async()=>{if(!confirm(`Hapus penerimaan ${receipt.receiptNumber}? Stok terkait akan dikoreksi otomatis.`))return;try{await deleteGoodsReceipt(receipt.id);navigate('/receipts')}catch(error:any){alert(error?.message||'Penerimaan tidak dapat dihapus.')}};
 const accept=async()=>{if(!confirm(`Terima barang ${receipt.receiptNumber}? Stok akan ditambahkan.`))return;try{await receiveGoods(receipt.id)}catch(error:any){alert(error?.message||'Gagal menerima barang.')}};
 const cancel=()=>{setForm(toForm(receipt));setEditing(false);setMenuOpen(false)};
 const fieldClass=`rounded border px-3 py-2 ${editing?'bg-white text-slate-900':'bg-[#e4e4e4] text-slate-700'}`;
 return <div className="relative min-h-[calc(100vh-134px)] overflow-hidden bg-[#f2f2f2] pb-20 [&_thead]:!bg-[#60778e]">
  <div className="mt-0.5 flex items-end border-b border-[#b8b8b8] bg-[#fafafa] pl-1.5"><button onClick={()=>navigate('/receipts')} title="Daftar Penerimaan" className="flex h-11 w-14 items-center justify-center rounded-t border border-b-0 border-[#45a90f] bg-[#5bc516] text-white"><List className="h-5 w-5"/></button><div className="ml-1 flex h-11 items-center gap-3 rounded-t border border-b-0 border-[#b8b8b8] border-t-2 border-t-blue-600 bg-[#f2f2f2] px-4 font-mono font-semibold text-blue-700">{receipt.receiptNumber}<button onClick={()=>navigate('/receipts')} title="Tutup"><X className="h-4 w-4"/></button></div></div>
  <div className="grid gap-4 bg-[#ededed] px-6 py-3 lg:grid-cols-[1fr_1fr_128px]">
   <div className="grid grid-cols-[150px_1fr] items-center gap-2 text-sm"><label className="font-medium">Terima dari <span className="text-red-600">*</span></label><select disabled={!editing||receipt.sourceType==='Transfer Gudang'} value={form.supplierId} onChange={event=>setForm({...form,supplierId:event.target.value})} className={fieldClass}><option value="">{receipt.sourceType==='Transfer Gudang'?'TRANSFER GUDANG':'Cari/Pilih Pemasok — boleh menyusul'}</option>{data.suppliers.filter(s=>s.isActive).map(s=><option key={s.id} value={s.id}>{s.code} - {s.name}</option>)}</select><label className="font-medium">Tanggal <span className="text-red-600">*</span></label><input disabled={!editing} type="date" value={form.date} onChange={event=>setForm({...form,date:event.target.value})} className={fieldClass}/><label className="font-medium">No Terima # <span className="text-red-600">*</span></label><input disabled={!editing} value={form.doNumber} onChange={event=>setForm({...form,doNumber:event.target.value.toUpperCase()})} className={`${fieldClass} font-mono`}/></div>
   <div className="grid grid-cols-[150px_1fr] content-start items-center gap-2 text-sm"><label>Gudang</label><select disabled={!editing} value={form.warehouseId} onChange={event=>setForm({...form,warehouseId:event.target.value})} className={fieldClass}>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><label>Diterima Oleh</label><select disabled={!editing} value={form.receivedById} onChange={event=>setForm({...form,receivedById:event.target.value})} className={fieldClass}>{receivingUsers.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><label>Cara Pengiriman</label><select disabled={!editing} value={form.deliveryMethod} onChange={event=>setForm({...form,deliveryMethod:event.target.value})} className={fieldClass}>{deliveryOptions.map(option=><option key={option}>{option}</option>)}</select></div>
   <div className="relative flex flex-col items-center gap-2"><div className="text-center text-xs text-slate-500">No Form #<b className="block font-mono text-blue-700">{receipt.receiptNumber}</b></div>{editing?<button disabled={saving} onClick={save} className="flex h-14 w-20 items-center justify-center gap-2 rounded bg-blue-700 text-white shadow disabled:opacity-50"><Save className="h-6 w-6"/><ChevronDown className="h-4 w-4"/></button>:<button onClick={()=>setMenuOpen(value=>!value)} className="flex h-14 w-20 items-center justify-center rounded bg-blue-100 text-blue-800"><FileText className="h-6 w-6"/></button>}<button onClick={()=>setMenuOpen(value=>!value)} title="Pilihan lainnya" className="flex h-10 w-20 items-center justify-center rounded border border-green-500 bg-green-200 text-green-700"><MoreHorizontal/></button>{menuOpen&&<div className="absolute right-4 top-full z-30 mt-1 w-48 rounded border bg-white p-1 shadow-xl">{!editing&&hasPermission('receipt:edit')&&<button onClick={()=>{setEditing(true);setMenuOpen(false)}} className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm hover:bg-blue-50"><Pencil className="h-4 w-4 text-blue-600"/>Edit Penerimaan</button>}{editing&&<button onClick={cancel} className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm hover:bg-slate-50"><X className="h-4 w-4"/>Batalkan Edit</button>}{receipt.status==='Draft'&&hasPermission('receipt:edit')&&<button onClick={accept} className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm hover:bg-green-50"><Package className="h-4 w-4 text-green-600"/>Terima Barang</button>}{receipt.status==='Diterima'&&receipt.sourceType!=='Transfer Gudang'&&hasPermission('purchase:view')&&<button onClick={()=>navigate('/purchase-invoices')} className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm hover:bg-blue-50"><FileText className="h-4 w-4 text-blue-600"/>Faktur Pembelian</button>}{hasPermission('receipt:delete')&&<button onClick={remove} className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm text-red-700 hover:bg-red-50"><Trash2 className="h-4 w-4"/>Hapus Penerimaan</button>}</div>}</div>
  </div>
  <div className="mx-2 mt-1 rounded border border-slate-300">
   <div className="flex flex-wrap items-center justify-between gap-2 border-b bg-white p-2"><div onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))setShowPicker(false)}} className="relative w-full max-w-md"><input disabled={!editing} value={search} onFocus={()=>setShowPicker(true)} onChange={event=>{setSearch(event.target.value);setShowPicker(true)}} placeholder={editing?'Cari/Pilih Barang & Jasa...':'Mode lihat — pilih Edit untuk mengubah'} className={`w-full rounded border px-3 py-2 pr-10 text-sm ${editing?'bg-white':'bg-[#e4e4e4]'}`}/><Search className="pointer-events-none absolute right-3 top-2.5 h-5 w-5"/>{editing&&showPicker&&<div className="absolute z-30 mt-1 max-h-64 w-full overflow-auto rounded border bg-white shadow-xl">{availableItems.map(item=><button key={item.id} onClick={()=>addLine(item)} className="flex w-full justify-between border-b px-3 py-2 text-left text-sm hover:bg-blue-50"><span><b>{item.code}</b> · {item.name}</span><span>{item.unit}</span></button>)}</div>}</div><h3 className="flex items-center gap-2 text-lg font-semibold"><Package className="h-5 w-5 text-blue-600"/>Rincian Barang <span className="text-red-600">*</span></h3></div>
   <div className="min-h-[420px] overflow-x-auto"><table className="min-w-full table-fixed text-sm" style={{width:columnWidths.reduce((sum,width)=>sum+width,52)}}><colgroup>{columnWidths.map((width,index)=><col key={index} style={{width}}/>)}<col style={{width:52}}/></colgroup><thead className="bg-slate-600 text-white"><tr>{['Kode #','Nama Barang','Kuantitas','Satuan'].map((label,index)=><th key={label} className={`relative p-2 ${index<2?'text-left':'text-center'} ${index===0?'rounded-tl-lg':''}`}>{label}<span onMouseDown={event=>resizeColumn(index,event)} title="Tarik untuk mengubah lebar kolom" className="absolute -right-1 top-0 z-10 h-full w-2 cursor-col-resize hover:bg-blue-300/60"/></th>)}<th className="rounded-tr-lg border-l border-slate-400 bg-slate-500"></th></tr></thead><tbody>{form.items.map(line=><tr key={line.id} tabIndex={0} onFocus={()=>setSelectedLineId(line.id)} onClick={()=>setSelectedLineId(line.id)} className={`cursor-pointer border-b outline-none ${selectedLineId===line.id?'bg-slate-200 ring-1 ring-inset ring-blue-400':'hover:bg-slate-50'}`}><td className="truncate p-2 font-mono">{line.itemCode}</td><td className="truncate p-2" title={line.itemName}>{line.itemName}</td><td className="p-2 text-center">{editing?<input type="number" min="1" value={line.qty} onClick={event=>event.stopPropagation()} onChange={event=>setForm({...form,items:form.items.map(item=>item.id===line.id?{...item,qty:Math.max(1,Number(event.target.value)||1)}:item)})} className="w-20 rounded border bg-white px-2 py-1 text-right"/>:line.qty}</td><td className="p-2 text-center">{line.unit}</td><td className="border-l border-slate-300 bg-slate-100 p-2 text-center">{editing&&<button onClick={event=>{event.stopPropagation();setForm({...form,items:form.items.filter(item=>item.id!==line.id)})}} title="Hapus barang" className="rounded border bg-white p-1 text-red-600"><Trash2 className="h-4 w-4"/></button>}</td></tr>)}</tbody></table>{selectedLine&&<div className="m-3 grid gap-2 rounded border border-slate-300 bg-slate-50 p-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-slate-500">Kode</span><b className="block font-mono">{selectedLine.itemCode}</b></div><div><span className="text-slate-500">Nama Barang</span><b className="block">{selectedLine.itemName}</b></div><div><span className="text-slate-500">Kategori</span><b className="block">{selectedMaster?.categoryName||'-'}</b></div><div><span className="text-slate-500">Merek / Stok</span><b className="block">{selectedMaster?.brand||'Universal'} · {selectedMaster?.stock??0} {selectedLine.unit}</b></div></div>}</div>
  </div>
 </div>;
}

function toForm(receipt:GoodsReceipt){return{date:receipt.date,doNumber:receipt.doNumber||'',warehouseId:receipt.warehouseId||'',supplierId:receipt.supplierId||'',deliveryMethod:receipt.deliveryMethod||'Diantar Supplier',deliveryOther:receipt.deliveryOther||'',shippingNotes:receipt.shippingNotes||'',notes:receipt.notes||'',receivedById:receipt.receivedById||'',items:receipt.items.map(item=>({...item})) as GoodsReceiptItem[],status:receipt.status}}
