import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Download, Search } from 'lucide-react';
import { useApp } from '../context/AppContext';

const money=(value:number)=>`Rp ${Number(value||0).toLocaleString('id-ID')}`;
const csv=(value:unknown)=>`"${String(value??'').replace(/"/g,'""')}"`;

export default function InventoryReport(){
  const {data,currentBranchId}=useApp();
  const [searchParams]=useSearchParams();
  const availabilityParam=searchParams.get('availability');
  const [warehouseId,setWarehouseId]=useState(''),[type,setType]=useState('Persediaan'),[availability,setAvailability]=useState(availabilityParam === 'ATTENTION' ? 'ATTENTION' : 'ALL'),[search,setSearch]=useState('');
  const warehouses=useMemo(()=>data.warehouses.filter(w=>w.isActive&&(currentBranchId==='ALL'||w.branchId===currentBranchId)),[data.warehouses,currentBranchId]);
  const quantity=(itemId:string)=>{
    if(warehouseId)return Number(data.warehouseStocks.find(s=>s.warehouseId===warehouseId&&s.itemId===itemId)?.quantity||0);
    const scopedIds=new Set(warehouses.map(w=>w.id));const stocks=data.warehouseStocks.filter(s=>s.itemId===itemId&&scopedIds.has(s.warehouseId));
    if(stocks.length)return stocks.reduce((sum,row)=>sum+Number(row.quantity||0),0);
    const item=data.items.find(i=>i.id===itemId);if(currentBranchId!=='ALL')return Number(item?.branchStocks?.[currentBranchId]?.stock||0);return Number(item?.stock||0);
  };
  const rows=useMemo(()=>data.items.filter(item=>(type==='ALL'||item.type===type)&&`${item.code} ${item.name} ${item.categoryName} ${item.brand} ${item.barcode||''}`.toLowerCase().includes(search.toLowerCase())).map(item=>({...item,quantity:quantity(item.id)})).filter(item=>availability==='ALL'||(availability==='AVAILABLE'?item.quantity>0:availability==='EMPTY'?item.quantity===0:availability==='ATTENTION'?item.quantity<=0:item.quantity<0)).sort((a,b)=>a.name.localeCompare(b.name,'id')),[data.items,data.warehouseStocks,warehouses,warehouseId,currentBranchId,type,availability,search]);
  const stockRows=rows.filter(r=>r.type==='Persediaan'),units=stockRows.reduce((s,r)=>s+r.quantity,0),value=stockRows.reduce((s,r)=>s+r.quantity*Number(r.purchasePrice||0),0),empty=stockRows.filter(r=>r.quantity<=0).length;
  const exportCsv=()=>{const h=['Kode','Nama','Jenis','Kategori','Merek','Gudang','Qty','Satuan','Harga Beli','Estimasi Nilai Stok'];const b=rows.map(r=>[r.code,r.name,r.type,r.categoryName,r.brand,data.warehouses.find(w=>w.id===warehouseId)?.name||'Semua Gudang',r.quantity,r.unit,r.purchasePrice,r.quantity*r.purchasePrice].map(csv).join(','));const blob=new Blob(['\uFEFF'+[h.map(csv).join(','),...b].join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='laporan_persediaan.csv';a.click();URL.revokeObjectURL(url)};
  return <div className="space-y-3 pb-4">
    <div className="flex justify-end"><button onClick={exportCsv} disabled={!rows.length} className="inline-flex h-9 items-center gap-2 rounded-lg border border-green-300 px-3 text-sm font-semibold text-green-700 disabled:opacity-40"><Download className="h-4 w-4"/>Export CSV</button></div>
    <div className="grid grid-cols-2 gap-2 lg:grid-cols-4"><Card label="Barang Ditampilkan" value={String(rows.length)} note={`${stockRows.length} persediaan`}/><Card label="Total Unit" value={units.toLocaleString('id-ID')} note="stok pada lingkup terpilih"/><Card label="Estimasi Nilai Stok" value={money(value)} note="qty × harga beli; bukan HPP historis"/><Card label="Stok Kosong/Minus" value={String(empty)} note="perlu perhatian"/></div>
    <div className="flex flex-wrap gap-2 border-b border-blue-200 pb-2"><label className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari kode, barcode, nama, kategori, merek..." className="h-9 w-full rounded-lg border pl-9 pr-3 text-sm"/></label><select value={warehouseId} onChange={e=>setWarehouseId(e.target.value)} className="h-9 rounded-lg border px-3 text-sm"><option value="">Semua Gudang</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} className="h-9 rounded-lg border px-3 text-sm"><option value="ALL">Semua Jenis</option><option>Persediaan</option><option>Jasa</option><option>Non Persediaan</option><option>Group</option></select><select value={availability} onChange={e=>setAvailability(e.target.value)} className="h-9 rounded-lg border px-3 text-sm"><option value="ALL">Semua Stok</option><option value="AVAILABLE">Tersedia</option><option value="EMPTY">Kosong</option><option value="NEGATIVE">Minus</option><option value="ATTENTION">Kosong / Minus</option></select></div>
    <div className="overflow-hidden rounded-xl border bg-white"><div className="max-h-[calc(100vh-330px)] overflow-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="sticky top-0 bg-blue-900 text-left text-xs uppercase text-white"><tr>{['Kode','Barang','Jenis','Kategori','Merek','Qty','Satuan','Harga Beli','Nilai'].map(x=><th key={x} className="px-3 py-2.5">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id} className="hover:bg-blue-50/40"><td className="px-3 py-2 font-mono text-xs text-blue-700">{r.code}</td><td className="px-3 font-semibold">{r.name}</td><td className="px-3">{r.type}</td><td className="px-3">{r.categoryName||'-'}</td><td className="px-3">{r.brand||'-'}</td><td className={`px-3 text-right font-bold ${r.quantity<=0&&r.type==='Persediaan'?'text-red-600':'text-gray-900'}`}>{r.type==='Jasa'?'-':r.quantity.toLocaleString('id-ID')}</td><td className="px-3">{r.unit}</td><td className="px-3 text-right">{money(r.purchasePrice)}</td><td className="px-3 text-right font-semibold">{r.type==='Persediaan'?money(r.quantity*r.purchasePrice):'-'}</td></tr>)}</tbody></table></div>{!rows.length&&<div className="p-12 text-center text-gray-400">Tidak ada barang sesuai filter.</div>}</div>
  </div>;
}
function Card({label,value,note}:{label:string;value:string;note:string}){return <div className="rounded-xl border bg-white p-3 shadow-sm"><p className="text-xs text-gray-500">{label}</p><p className="truncate text-lg font-bold text-gray-900">{value}</p><p className="text-[11px] text-gray-400">{note}</p></div>}
