import { useEffect, useMemo, useState } from 'react';
import { Activity, Banknote, CalendarCheck, Clock3, Coins, Edit, Plus, RefreshCw, Save, Settings2, Trash2, Users, X } from 'lucide-react';
import { api } from '../lib/apiClient';
import { useApp } from '../context/AppContext';
import { localDateKey } from '../lib/date';
import IndonesianDateInput from '../components/IndonesianDateInput';

type Tab = 'summary' | 'attendance' | 'rules' | 'calculation' | 'history';
type Attendance = { id:string;attendanceDate:string;userId:string;userName:string;branchId:string;status:string;checkIn?:string;checkOut?:string;lateMinutes:number;notes?:string };
type Rule = { id:string;name:string;metric:string;calculationMode:string;operatorSymbol:string;thresholdValue:number;resultType:string;resultValue:number;branchId?:string;isActive:boolean;validFrom?:string;validUntil?:string };
type TechnicianCalc = { userId:string;userName:string;roleName:string;metrics:Record<string,number>;points:number;rawPoints:number;fixedBonus:number;poolBonus:number;bonus:number };
type Calculation = { period:string;branchId:string;bonusPool:number;totalPoints:number;totalBonus:number;technicians:TechnicianCalc[] };
type Run = { id:string;period:string;branchId:string;branchName:string;bonusPool:number;totalPoints:number;totalBonus:number;status:string;createdByName?:string;snapshot?:Calculation };
type Daily = { date:string;vehicles:number;completed:number;woValue:number;invoiceValue:number;paid:number;cashReceived:number;deposited:number;unsubmittedDaily:number;technicians:string[] };
type Payload = { users:Array<{id:string;name:string;roleName:string;branchId:string}>;attendance:Attendance[];rules:Rule[];runs:Run[];daily:Daily[];depositSummary:any[];calculation:Calculation|null };

const money = (value:number) => `Rp ${Number(value || 0).toLocaleString('id-ID')}`;
const today = localDateKey();
const currentPeriod = today.slice(0,7);
const metricLabels:Record<string,string> = {
  attendance_days:'Hari hadir', completed_work_orders:'WO selesai', paid_revenue:'Pendapatan terbayar', late_minutes:'Menit terlambat', absence_days:'Hari alpha',
};
const blankRule = { name:'',metric:'attendance_days',calculationMode:'per_unit',operatorSymbol:'gte',thresholdValue:0,resultType:'points',resultValue:1,branchId:'',isActive:true,validFrom:'',validUntil:'' };

export default function PerformanceBonus(){
  const { data:appData,currentUser,currentBranchId,hasPermission }=useApp();
  const [tab,setTab]=useState<Tab>('summary');
  const [period,setPeriod]=useState(currentPeriod);
  const [branchId,setBranchId]=useState(currentBranchId==='ALL'?'ALL':currentBranchId);
  const [payload,setPayload]=useState<Payload>({users:[],attendance:[],rules:[],runs:[],daily:[],depositSummary:[],calculation:null});
  const [loading,setLoading]=useState(false);
  const [attendanceOpen,setAttendanceOpen]=useState(false);
  const [attendanceForm,setAttendanceForm]=useState({attendanceDate:today,userId:'',branchId:'',status:'Hadir',checkIn:'08:00',checkOut:'17:00',lateMinutes:0,notes:''});
  const [ruleOpen,setRuleOpen]=useState(false),[editingRule,setEditingRule]=useState<Rule|null>(null),[ruleForm,setRuleForm]=useState<any>(blankRule);
  const [bonusPool,setBonusPool]=useState(0),[calculation,setCalculation]=useState<Calculation|null>(null);
  const canEdit=Boolean(currentUser?.isOwner||hasPermission('settings:edit'));
  const activeBranches=appData.branches.filter(branch=>branch.isActive);
  const effectiveBranch=branchId==='ALL'?'':branchId;

  const load=async()=>{setLoading(true);const result=await api.get(`performance-bonus?period=${encodeURIComponent(period)}&branchId=${encodeURIComponent(branchId)}`);if(result.success){setPayload(result.data as Payload);if(!calculation)setCalculation((result.data as Payload).calculation);}else window.alert(result.message);setLoading(false)};
  useEffect(()=>{void load()},[period,branchId]);
  useEffect(()=>{if(branchId!=='ALL')setAttendanceForm(form=>({...form,branchId}))},[branchId]);

  const deposit=useMemo(()=>payload.depositSummary.filter(row=>branchId==='ALL'||row.branchId===branchId).reduce((sum,row)=>sum+Number(row.unsubmitted||0),0),[payload.depositSummary,branchId]);
  const totals=useMemo(()=>payload.daily.reduce((sum,row)=>({vehicles:sum.vehicles+row.vehicles,completed:sum.completed+row.completed,invoice:sum.invoice+row.invoiceValue,paid:sum.paid+row.paid}),{vehicles:0,completed:0,invoice:0,paid:0}),[payload.daily]);
  const presentToday=payload.attendance.filter(row=>row.attendanceDate===today&&row.status==='Hadir');

  const saveAttendance=async(event:React.FormEvent)=>{event.preventDefault();if(!attendanceForm.branchId)return window.alert('Pilih cabang.');const result=await api.create('performance-bonus',{type:'attendance',...attendanceForm});if(!result.success)return window.alert(result.message);setAttendanceOpen(false);await load()};
  const openRule=(rule?:Rule)=>{setEditingRule(rule||null);setRuleForm(rule?{...rule,branchId:rule.branchId||'',validFrom:rule.validFrom||'',validUntil:rule.validUntil||''}:blankRule);setRuleOpen(true)};
  const saveRule=async(event:React.FormEvent)=>{event.preventDefault();const body={type:'rule',...ruleForm};const result=editingRule?await api.update('performance-bonus',editingRule.id,body):await api.create('performance-bonus',body);if(!result.success)return window.alert(result.message);setRuleOpen(false);await load()};
  const remove=async(id:string,label:string)=>{if(!window.confirm(`Hapus ${label}?`))return;const result=await api.remove('performance-bonus',id);if(!result.success)return window.alert(result.message);await load()};
  const calculate=async()=>{if(!effectiveBranch)return window.alert('Pilih satu cabang sebelum menghitung bonus.');const result=await api.create('performance-bonus',{type:'calculate',period,branchId:effectiveBranch,bonusPool});if(!result.success)return window.alert(result.message);setCalculation(result.data?.calculation||null);await load();setTab('calculation')};
  const setRunStatus=async(run:Run,status:string)=>{if(!window.confirm(`${status} bonus periode ${run.period}?`))return;const result=await api.update('performance-bonus',run.id,{type:'runStatus',status});if(!result.success)return window.alert(result.message);await load()};

  const tabs:Array<{id:Tab;label:string;icon:any}>=[
    {id:'summary',label:'Ringkasan',icon:Activity},{id:'attendance',label:'Kehadiran',icon:CalendarCheck},{id:'rules',label:'Rules Bonus',icon:Settings2},{id:'calculation',label:'Perhitungan',icon:Coins},{id:'history',label:'Riwayat',icon:Clock3},
  ];
  return <div className="space-y-3">
    <div className="flex flex-wrap items-center gap-2 border-b border-blue-600">
      {tabs.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setTab(item.id)} className={`flex items-center gap-2 rounded-t-lg border border-b-0 px-4 py-3 font-semibold ${tab===item.id?'border-blue-600 bg-blue-600 text-white':'border-slate-300 bg-slate-100 text-slate-600'}`}><Icon className="h-4 w-4"/>{item.label}</button>})}
      <div className="ml-auto flex items-center gap-2 pb-1">
        <input type="month" value={period} onChange={event=>{setPeriod(event.target.value);setCalculation(null)}} className="rounded-lg border px-3 py-2"/>
        <select value={branchId} onChange={event=>{setBranchId(event.target.value);setCalculation(null)}} className="rounded-lg border px-3 py-2"><option value="ALL">Semua Cabang</option>{activeBranches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</select>
        <button onClick={()=>void load()} className="rounded-lg border p-2.5 text-blue-700"><RefreshCw className={`h-5 w-5 ${loading?'animate-spin':''}`}/></button>
      </div>
    </div>

    {tab==='summary'&&<>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
        <Stat label="Mobil masuk" value={totals.vehicles.toLocaleString('id-ID')} note={`${totals.completed} selesai`} icon={Activity} tone="blue"/>
        <Stat label="Nilai faktur" value={money(totals.invoice)} note="Faktur final periode" icon={Save} tone="purple"/>
        <Stat label="Pembayaran diterima" value={money(totals.paid)} note="Dasar pendapatan bonus" icon={Coins} tone="green"/>
        <Stat label="Tunai belum disetor" value={money(deposit)} note="Semua penerimaan tunai aktif" icon={Banknote} tone="red"/>
        <Stat label="Teknisi hadir hari ini" value={String(presentToday.length)} note={presentToday.map(row=>row.userName).join(', ')||'Belum dicatat'} icon={Users} tone="amber"/>
      </div>
      <Section title="Operasional Harian" note="Jumlah mobil, transaksi, dan teknisi yang hadir pada tanggal tersebut.">
        <Table headers={['Tanggal','Mobil','Selesai','Nilai WO','Faktur Final','Pembayaran','Tunai','Setoran','Sisa Harian','Teknisi Hadir']} empty={!payload.daily.length}>
          {payload.daily.map(row=><tr key={row.date} className="border-t"><td className="p-3 font-semibold">{row.date}</td><td className="p-3">{row.vehicles}</td><td className="p-3 text-green-700">{row.completed}</td><td className="p-3">{money(row.woValue)}</td><td className="p-3">{money(row.invoiceValue)}</td><td className="p-3 font-semibold text-green-700">{money(row.paid)}</td><td className="p-3">{money(row.cashReceived)}</td><td className="p-3">{money(row.deposited)}</td><td className="p-3 font-semibold text-red-600">{money(row.unsubmittedDaily)}</td><td className="p-3">{row.technicians.join(', ')||'-'}</td></tr>)}
        </Table>
      </Section>
    </>}

    {tab==='attendance'&&<Section title="Kehadiran Teknisi" note="Kehadiran menjadi salah satu sumber perhitungan bonus." action={canEdit?<button onClick={()=>setAttendanceOpen(true)} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-white"><Plus className="h-4 w-4"/>Catat Kehadiran</button>:undefined}>
      <Table headers={['Tanggal','Teknisi','Cabang','Status','Masuk','Pulang','Terlambat','Catatan','Aksi']} empty={!payload.attendance.length}>{payload.attendance.map(row=><tr key={row.id} className="border-t"><td className="p-3">{row.attendanceDate}</td><td className="p-3 font-semibold">{row.userName}</td><td className="p-3">{appData.branches.find(branch=>branch.id===row.branchId)?.name||row.branchId}</td><td className="p-3"><Badge value={row.status}/></td><td className="p-3">{row.checkIn||'-'}</td><td className="p-3">{row.checkOut||'-'}</td><td className="p-3">{row.lateMinutes||0} menit</td><td className="p-3">{row.notes||'-'}</td><td className="p-3">{canEdit&&<button onClick={()=>void remove(row.id,'catatan kehadiran')} className="text-red-600"><Trash2 className="h-4 w-4"/></button>}</td></tr>)}</Table>
    </Section>}

    {tab==='rules'&&<Section title="Rules Bonus Custom" note="Rule aktif otomatis dipakai pada perhitungan periode berikutnya. Snapshot periode lama tidak berubah." action={canEdit?<button onClick={()=>openRule()} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-white"><Plus className="h-4 w-4"/>Rule Baru</button>:undefined}>
      <Table headers={['Rule','Dasar','Cara Hitung','Hasil','Cabang','Masa Berlaku','Status','Aksi']} empty={!payload.rules.length}>{payload.rules.map(rule=><tr key={rule.id} className={`border-t ${!rule.isActive?'opacity-50':''}`}><td className="p-3 font-semibold">{rule.name}</td><td className="p-3">{metricLabels[rule.metric]||rule.metric}</td><td className="p-3">{rule.calculationMode==='per_unit'?'Per unit':'Jika syarat terpenuhi'}{rule.thresholdValue>0?` · batas ${rule.metric==='paid_revenue'?money(rule.thresholdValue):rule.thresholdValue}`:''}</td><td className={`p-3 font-bold ${rule.resultValue<0?'text-red-600':'text-green-700'}`}>{rule.resultValue>0?'+':''}{rule.resultType==='fixed'?money(rule.resultValue):`${rule.resultValue} poin`}</td><td className="p-3">{appData.branches.find(branch=>branch.id===rule.branchId)?.name||'Semua'}</td><td className="p-3">{rule.validFrom||'Bebas'} — {rule.validUntil||'Bebas'}</td><td className="p-3"><Badge value={rule.isActive?'Aktif':'Nonaktif'}/></td><td className="p-3">{canEdit&&<div className="flex gap-2"><button onClick={()=>openRule(rule)} className="text-blue-600"><Edit className="h-4 w-4"/></button>{!rule.id.startsWith('BONUS-')&&<button onClick={()=>void remove(rule.id,'rule bonus')} className="text-red-600"><Trash2 className="h-4 w-4"/></button>}</div>}</td></tr>)}</Table>
    </Section>}

    {tab==='calculation'&&<>
      <div className="flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4"><label className="text-sm">Dana bonus periode<input type="number" min="0" value={bonusPool} onChange={event=>setBonusPool(Number(event.target.value))} className="mt-1 block w-64 rounded-lg border px-3 py-2 font-bold"/></label><button onClick={()=>void calculate()} disabled={!effectiveBranch} className="flex items-center gap-2 rounded-lg bg-blue-600 px-5 py-2.5 text-white disabled:bg-slate-300"><Coins className="h-4 w-4"/>Hitung & Simpan Draft</button><p className="text-sm text-slate-500">Pilih satu cabang. Dana dibagi berdasarkan poin setelah bonus nominal tetap.</p></div>
      <Section title="Rincian Perhitungan" note={calculation?`${calculation.totalPoints} total poin · ${money(calculation.totalBonus)} total bonus`:'Masukkan dana bonus lalu jalankan perhitungan.'}>
        <Table headers={['Teknisi','Hadir','WO Selesai','Pendapatan Terbayar','Terlambat','Alpha','Poin','Bonus Tetap','Bagian Pool','Total Bonus']} empty={!calculation?.technicians.length}>{calculation?.technicians.map(row=><tr key={row.userId} className="border-t"><td className="p-3"><b>{row.userName}</b><small className="block text-slate-500">{row.roleName}</small></td><td className="p-3">{row.metrics.attendance_days||0}</td><td className="p-3">{row.metrics.completed_work_orders||0}</td><td className="p-3">{money(row.metrics.paid_revenue||0)}</td><td className="p-3">{row.metrics.late_minutes||0} mnt</td><td className="p-3">{row.metrics.absence_days||0}</td><td className="p-3 font-bold text-blue-700">{row.points}</td><td className="p-3">{money(row.fixedBonus)}</td><td className="p-3">{money(row.poolBonus)}</td><td className="p-3 font-bold text-green-700">{money(row.bonus)}</td></tr>)}</Table>
      </Section>
    </>}

    {tab==='history'&&<Section title="Riwayat Bonus" note="Periode yang disetujui terkunci sebagai snapshot. Owner dapat menandai pembayaran bonus.">
      <Table headers={['Periode','Cabang','Dana Bonus','Poin','Total Bonus','Status','Dibuat Oleh','Aksi']} empty={!payload.runs.length}>{payload.runs.map(run=><tr key={run.id} className="border-t"><td className="p-3 font-semibold">{run.period}</td><td className="p-3">{run.branchName||run.branchId}</td><td className="p-3">{money(run.bonusPool)}</td><td className="p-3">{run.totalPoints}</td><td className="p-3 font-bold text-green-700">{money(run.totalBonus)}</td><td className="p-3"><Badge value={run.status}/></td><td className="p-3">{run.createdByName||'-'}</td><td className="p-3">{currentUser?.isOwner&&<div className="flex gap-2">{run.status==='Draft'&&<button onClick={()=>void setRunStatus(run,'Disetujui')} className="rounded bg-blue-600 px-3 py-1.5 text-white">Setujui</button>}{run.status==='Disetujui'&&<button onClick={()=>void setRunStatus(run,'Dibayar')} className="rounded bg-green-600 px-3 py-1.5 text-white">Tandai Dibayar</button>}</div>}</td></tr>)}</Table>
    </Section>}

    {attendanceOpen&&<Modal title="Catat Kehadiran" close={()=>setAttendanceOpen(false)}><form onSubmit={saveAttendance} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Field label="Tanggal"><IndonesianDateInput required max={today} value={attendanceForm.attendanceDate} onChange={attendanceDate=>setAttendanceForm({...attendanceForm,attendanceDate})} className="h-10 w-full"/></Field><Field label="Cabang"><select required value={attendanceForm.branchId} onChange={e=>setAttendanceForm({...attendanceForm,branchId:e.target.value})}><option value="">Pilih cabang</option>{activeBranches.map(branch=><option value={branch.id} key={branch.id}>{branch.name}</option>)}</select></Field><Field label="Teknisi"><select required value={attendanceForm.userId} onChange={e=>setAttendanceForm({...attendanceForm,userId:e.target.value})}><option value="">Pilih pengguna</option>{payload.users.map(user=><option value={user.id} key={user.id}>{user.name} · {user.roleName}</option>)}</select></Field><Field label="Status"><select value={attendanceForm.status} onChange={e=>setAttendanceForm({...attendanceForm,status:e.target.value})}>{['Hadir','Izin','Sakit','Libur','Alpha'].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Jam masuk"><input type="time" value={attendanceForm.checkIn} onChange={e=>setAttendanceForm({...attendanceForm,checkIn:e.target.value})}/></Field><Field label="Jam pulang"><input type="time" value={attendanceForm.checkOut} onChange={e=>setAttendanceForm({...attendanceForm,checkOut:e.target.value})}/></Field><Field label="Terlambat (menit)"><input type="number" min="0" value={attendanceForm.lateMinutes} onChange={e=>setAttendanceForm({...attendanceForm,lateMinutes:Number(e.target.value)})}/></Field></div><Field label="Catatan"><textarea value={attendanceForm.notes} onChange={e=>setAttendanceForm({...attendanceForm,notes:e.target.value})}/></Field><ModalActions cancel={()=>setAttendanceOpen(false)}/></form></Modal>}
    {ruleOpen&&<Modal title={editingRule?'Edit Rule Bonus':'Rule Bonus Baru'} close={()=>setRuleOpen(false)}><form onSubmit={saveRule} className="space-y-3"><Field label="Nama rule"><input required value={ruleForm.name} onChange={e=>setRuleForm({...ruleForm,name:e.target.value})}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Dasar perhitungan"><select value={ruleForm.metric} onChange={e=>setRuleForm({...ruleForm,metric:e.target.value})}>{Object.entries(metricLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></Field><Field label="Cara hitung"><select value={ruleForm.calculationMode} onChange={e=>setRuleForm({...ruleForm,calculationMode:e.target.value})}><option value="per_unit">Per unit</option><option value="threshold">Sekali jika syarat terpenuhi</option></select></Field><Field label="Batas / pembagi"><input type="number" value={ruleForm.thresholdValue} onChange={e=>setRuleForm({...ruleForm,thresholdValue:Number(e.target.value)})}/></Field><Field label="Hasil"><select value={ruleForm.resultType} onChange={e=>setRuleForm({...ruleForm,resultType:e.target.value})}><option value="points">Poin</option><option value="fixed">Nominal tetap</option></select></Field><Field label="Nilai hasil"><input type="number" step="0.5" value={ruleForm.resultValue} onChange={e=>setRuleForm({...ruleForm,resultValue:Number(e.target.value)})}/></Field><Field label="Cabang"><select value={ruleForm.branchId} onChange={e=>setRuleForm({...ruleForm,branchId:e.target.value})}><option value="">Semua cabang</option>{activeBranches.map(branch=><option value={branch.id} key={branch.id}>{branch.name}</option>)}</select></Field><Field label="Mulai berlaku"><IndonesianDateInput value={ruleForm.validFrom||''} onChange={validFrom=>setRuleForm({...ruleForm,validFrom})} className="h-10 w-full"/></Field><Field label="Berakhir"><IndonesianDateInput value={ruleForm.validUntil||''} onChange={validUntil=>setRuleForm({...ruleForm,validUntil})} className="h-10 w-full"/></Field></div><label className="flex items-center gap-2"><input type="checkbox" checked={ruleForm.isActive} onChange={e=>setRuleForm({...ruleForm,isActive:e.target.checked})}/>Aktif</label><ModalActions cancel={()=>setRuleOpen(false)}/></form></Modal>}
  </div>
}

function Stat({label,value,note,icon:Icon,tone}:{label:string;value:string;note:string;icon:any;tone:string}){const tones:any={blue:'bg-blue-50 text-blue-700',purple:'bg-purple-50 text-purple-700',green:'bg-green-50 text-green-700',red:'bg-red-50 text-red-700',amber:'bg-amber-50 text-amber-700'};return <div className="rounded-xl border bg-white p-4"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p></div><span className={`grid h-10 w-10 place-items-center rounded-lg ${tones[tone]}`}><Icon className="h-5 w-5"/></span></div><p className="mt-2 truncate text-xs text-slate-500" title={note}>{note}</p></div>}
function Section({title,note,action,children}:{title:string;note:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="rounded-xl border bg-white"><header className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="font-bold text-slate-900">{title}</h2><p className="text-sm text-slate-500">{note}</p></div>{action}</header>{children}</section>}
function Table({headers,empty,children}:{headers:string[];empty:boolean;children:React.ReactNode}){return <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-blue-900 text-white"><tr>{headers.map(header=><th key={header} className="whitespace-nowrap p-3 text-left">{header}</th>)}</tr></thead><tbody>{children}{empty&&<tr><td colSpan={headers.length} className="p-10 text-center text-slate-500">Belum ada data pada periode ini.</td></tr>}</tbody></table></div>}
function Badge({value}:{value:string}){const good=['Hadir','Aktif','Disetujui','Dibayar'].includes(value),bad=['Alpha','Nonaktif'].includes(value);return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${good?'bg-green-100 text-green-700':bad?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{value}</span>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white"><header className="flex items-center justify-between border-b p-4"><b>{title}</b><button onClick={close}><X/></button></header><div className="p-5">{children}</div></div></div>}
function Field({label,children}:{label:string;children:React.ReactElement}){return <label className="block text-sm">{label}<span className="mt-1 block [&>*]:w-full [&>*]:rounded-lg [&>*]:border [&>*]:px-3 [&>*]:py-2.5">{children}</span></label>}
function ModalActions({cancel}:{cancel:()=>void}){return <div className="flex justify-end gap-2 border-t pt-4"><button type="button" onClick={cancel} className="rounded-lg border px-4 py-2">Batal</button><button className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-white"><Save className="h-4 w-4"/>Simpan</button></div>}
