import { useMemo, useState } from 'react';
import { Download, Search } from 'lucide-react';
import { useApp } from '../context/AppContext';
import IndonesianDateInput from '../components/IndonesianDateInput';

const money = (value: number) => `Rp ${Number(value || 0).toLocaleString('id-ID')}`;
const localDate = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const csv = (value: unknown) => `"${String(value ?? '').replace(/"/g, '""')}"`;

export default function PurchaseReport() {
  const { data, currentBranchId } = useApp(); const now = new Date();
  const [from, setFrom] = useState(localDate(new Date(now.getFullYear(), now.getMonth(), 1))), [to, setTo] = useState(localDate(now));
  const [branchId, setBranchId] = useState(currentBranchId === 'ALL' ? '' : currentBranchId), [status, setStatus] = useState('ALL'), [search, setSearch] = useState('');
  const rows = useMemo(() => data.purchaseInvoices.filter(row => {
    const scope = currentBranchId === 'ALL' ? branchId : currentBranchId;
    return (!scope || row.branchId === scope) && (!from || row.date >= from) && (!to || row.date <= to) && (status === 'ALL' || row.status === status) && `${row.invoiceNumber} ${row.supplierInvoiceNumber} ${row.supplierName}`.toLowerCase().includes(search.toLowerCase());
  }).sort((a,b) => b.date.localeCompare(a.date)), [data.purchaseInvoices,currentBranchId,branchId,from,to,status,search]);
  const total = rows.filter(r => r.status !== 'Batal').reduce((s,r)=>s+r.total,0), paid = rows.reduce((s,r)=>s+r.paidAmount,0), debt = Math.max(0,total-paid);
  const exportCsv=()=>{const header=['Tanggal','No Internal','No Supplier','Cabang','Supplier','Total','Dibayar','Utang','Jatuh Tempo','Status'];const body=rows.map(r=>[r.date,r.invoiceNumber,r.supplierInvoiceNumber,data.branches.find(b=>b.id===r.branchId)?.name||'',r.supplierName,r.total,r.paidAmount,Math.max(0,r.total-r.paidAmount),r.dueDate,r.status].map(csv).join(','));const blob=new Blob(['\uFEFF'+[header.map(csv).join(','),...body].join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`laporan_pembelian_${from}_${to}.csv`;a.click();URL.revokeObjectURL(url)};
  const setMonth=(offset:number)=>{const d=new Date();const start=new Date(d.getFullYear(),d.getMonth()+offset,1),end=offset===0?d:new Date(d.getFullYear(),d.getMonth(),0);setFrom(localDate(start));setTo(localDate(end))};
  return <div className="space-y-3 pb-4">
    <div className="flex justify-end"><button onClick={exportCsv} disabled={!rows.length} className="inline-flex h-9 items-center gap-2 rounded-lg border border-green-300 px-3 text-sm font-semibold text-green-700 disabled:opacity-40"><Download className="h-4 w-4"/>Export CSV</button></div>
    <div className="grid grid-cols-2 gap-2 lg:grid-cols-4"><Card label="Total Pembelian" value={money(total)} note={`${rows.length} faktur`}/><Card label="Dibayar" value={money(paid)} note={`${Math.round(total?paid/total*100:0)}% dibayar`}/><Card label="Utang Supplier" value={money(debt)} note={`${rows.filter(r=>['Belum Lunas','Sebagian'].includes(r.status)).length} belum lunas`}/><Card label="Jatuh Tempo" value={String(rows.filter(r=>r.dueDate<localDate()&&!['Lunas','Batal'].includes(r.status)).length)} note="faktur terlambat"/></div>
    <div className="flex flex-wrap gap-2 border-b border-blue-200 pb-2"><label className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari faktur atau supplier..." className="h-9 w-full rounded-lg border pl-9 pr-3 text-sm"/></label>{currentBranchId==='ALL'&&<select value={branchId} onChange={e=>setBranchId(e.target.value)} className="h-9 rounded-lg border px-3 text-sm"><option value="">Semua Cabang</option>{data.branches.filter(b=>b.isActive).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}<select value={status} onChange={e=>setStatus(e.target.value)} className="h-9 rounded-lg border px-3 text-sm"><option value="ALL">Semua Status</option><option>Belum Lunas</option><option>Sebagian</option><option>Lunas</option><option>Batal</option></select><IndonesianDateInput value={from} onChange={setFrom} className="h-9 w-36 text-sm"/><IndonesianDateInput value={to} onChange={setTo} className="h-9 w-36 text-sm"/><button onClick={()=>setMonth(0)} className="rounded-lg border px-3 text-xs">Bulan Ini</button><button onClick={()=>setMonth(-1)} className="rounded-lg border px-3 text-xs">Bulan Lalu</button></div>
    <div className="overflow-hidden rounded-xl border bg-white"><div className="max-h-[calc(100vh-330px)] overflow-auto"><table className="w-full min-w-[1150px] text-sm"><thead className="sticky top-0 bg-blue-900 text-left text-xs uppercase text-white"><tr>{['Tanggal / Nomor','Cabang','Supplier','No. Supplier','Jatuh Tempo','Total','Dibayar','Utang','Status'].map(x=><th key={x} className="px-3 py-2.5">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id} className="hover:bg-blue-50/40"><td className="px-3 py-2"><b className="text-blue-700">{r.invoiceNumber}</b><small className="block text-gray-500">{r.date}</small></td><td className="px-3">{data.branches.find(b=>b.id===r.branchId)?.name||'-'}</td><td className="px-3 font-semibold">{r.supplierName}</td><td className="px-3">{r.supplierInvoiceNumber||'-'}</td><td className={`px-3 ${r.dueDate<localDate()&&!['Lunas','Batal'].includes(r.status)?'font-semibold text-red-600':''}`}>{r.dueDate}</td><td className="px-3 font-semibold">{money(r.total)}</td><td className="px-3 text-green-700">{money(r.paidAmount)}</td><td className="px-3 font-semibold text-amber-700">{money(Math.max(0,r.total-r.paidAmount))}</td><td className="px-3">{r.status}</td></tr>)}</tbody></table></div>{!rows.length&&<div className="p-12 text-center text-gray-400">Tidak ada pembelian sesuai filter.</div>}</div>
  </div>;
}
function Card({label,value,note}:{label:string;value:string;note:string}){return <div className="rounded-xl border bg-white p-3 shadow-sm"><p className="text-xs text-gray-500">{label}</p><p className="truncate text-lg font-bold text-gray-900">{value}</p><p className="text-[11px] text-gray-400">{note}</p></div>}
