import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ClipboardCheck, Eye, FilePlus2, Play, Printer, Save, Search, Send, Trash2, X } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../lib/apiClient';
import { localDateKey } from '../lib/date';

type CountRow={id:number;itemId:string;code:string;name:string;categoryName:string;unit:string;systemQuantity:number;count1:number|null;count2:number|null;finalQuantity:number|null;variance:number|null};
type CountResult={id:string;resultNumber:string;date:string;status:string;adjustmentId?:string|null;adjustmentNumber?:string|null;notes?:string};
type CountOrder={id:string;orderNumber:string;orderDate:string;startDate:string;warehouseId:string;warehouseCode:string;warehouseName:string;branchId:string;branchName:string;categoryId?:string|null;assignedUserId:string;assignedUserName:string;status:string;notes:string;createdAt:string;result?:CountResult|null;rows?:CountRow[]};
const statusTone:Record<string,string>={'Menunggu Eksekusi':'bg-amber-100 text-amber-800','Dalam Penghitungan':'bg-blue-100 text-blue-800','Selesai':'bg-emerald-100 text-emerald-800','Dibatalkan':'bg-red-100 text-red-800'};
const dateLabel=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'});
const escapeHtml=(value:unknown)=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');

export default function StockCountSheetReport(){
 const{data,currentUser,currentBranchId}=useApp();
 const canPost=Boolean(currentUser?.isOwner||currentUser?.permissions?.includes('stock_opname:post'));
 const[orders,setOrders]=useState<CountOrder[]>([]),[selected,setSelected]=useState<CountOrder|null>(null),[showNew,setShowNew]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[search,setSearch]=useState('');
 const[form,setForm]=useState({startDate:localDateKey(),branchId:currentBranchId==='ALL'?(currentUser?.branchId||''):currentBranchId,warehouseId:'',categoryId:'',assignedUserId:currentUser?.id||'',notes:''});
 const branches=useMemo(()=>data.branches.filter(x=>x.isActive),[data.branches]);
 const warehouses=useMemo(()=>data.warehouses.filter(x=>x.isActive&&!x.isSystem&&(!form.branchId||x.branchId===form.branchId)),[data.warehouses,form.branchId]);
 const users=useMemo(()=>data.users.filter(x=>x.isActive&&(!form.branchId||x.isOwner||x.branchId===form.branchId||x.branchIds?.includes(form.branchId))),[data.users,form.branchId]);
 const filtered=orders.filter(x=>`${x.orderNumber} ${x.warehouseName} ${x.assignedUserName} ${x.status}`.toLowerCase().includes(search.toLowerCase()));
 const loadOrders=async()=>{setLoading(true);try{const r=await api.get<CountOrder[]>('stock-opnames');if(!r.success)throw new Error(r.message);setOrders(r.data||[]);}catch(e:any){setMessage(e?.message||'Daftar gagal dimuat.');}finally{setLoading(false);}};
 useEffect(()=>{void loadOrders();},[]);
 useEffect(()=>{if(form.warehouseId&&!warehouses.some(x=>x.id===form.warehouseId))setForm(x=>({...x,warehouseId:''}));},[warehouses,form.warehouseId]);
 const openDetail=async(id:string)=>{setLoading(true);try{const r=await api.get<CountOrder>(`stock-opnames/${id}`);if(!r.success||!r.data)throw new Error(r.message);setSelected(r.data);}catch(e:any){setMessage(e?.message||'Detail gagal dimuat.');}finally{setLoading(false);}};
 const createOrder=async()=>{if(!form.warehouseId||!form.assignedUserId)return setMessage('Gudang dan petugas wajib dipilih.');setLoading(true);try{const r=await api.create('stock-opnames',form);if(!r.success)throw new Error(r.message);setShowNew(false);await loadOrders();const created=r.data as {id?:string}|undefined;if(created?.id)await openDetail(created.id);}catch(e:any){setMessage(e?.message||'Perintah gagal dibuat.');}finally{setLoading(false);}};
 const action=async(type:'start'|'save-result'|'post-result')=>{if(!selected)return;setLoading(true);try{const r=await api.update('stock-opnames',selected.id,{action:type,rows:selected.rows||[],notes:selected.result?.notes||''});if(!r.success)throw new Error(r.message);await loadOrders();await openDetail(selected.id);setMessage(r.message||'Stok Opname diperbarui.');}catch(e:any){setMessage(e?.message||'Proses gagal.');}finally{setLoading(false);}};
 const remove=async(target:'order'|'result')=>{if(!selected||!confirm(`Hapus ${target==='result'?'Hasil':'Perintah'} Stok Opname?`))return;setLoading(true);try{const r=await api.removeWithBody('stock-opnames',selected.id,{target});if(!r.success)throw new Error(r.message);if(target==='result')await openDetail(selected.id);else setSelected(null);await loadOrders();setMessage(r.message||'Dokumen dihapus.');}catch(e:any){setMessage(e?.message||'Tidak dapat dihapus.');}finally{setLoading(false);}};
 const updateCount=(id:number,key:'count1'|'count2',value:string)=>setSelected(current=>current?{...current,rows:(current.rows||[]).map(row=>row.id===id?{...row,[key]:value===''?null:Math.max(0,Number(value)||0)}:row)}:current);
 const grouped=useMemo(()=>{const map=new Map<string,CountRow[]>();(selected?.rows||[]).forEach(row=>map.set(row.categoryName,[...(map.get(row.categoryName)||[]),row]));return[...map.entries()];},[selected]);
 const printSheet=()=>{if(!selected?.result)return;const popup=window.open('','_blank','width=1000,height=800');if(!popup)return;const body=grouped.map(([cat,rows])=>`<tr class="group"><td colspan="7">${escapeHtml(cat)}</td></tr>${rows.map(row=>`<tr><td>${escapeHtml(row.code)}</td><td>${escapeHtml(row.name)}</td><td class="num">${row.systemQuantity}</td><td>${escapeHtml(row.unit)}</td><td>${row.count1??'<span></span>'}</td><td>${row.count2??'<span></span>'}</td><td>${row.variance??''}</td></tr>`).join('')}`).join('');popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(selected.result.resultNumber)}</title><style>@page{size:A4 portrait;margin:13mm}body{font-family:Arial}.head{text-align:center}.head h1{color:#a00039}.meta{text-align:right;font-size:9px;margin:15px 0}table{width:100%;border-collapse:collapse;font-size:10px}thead{display:table-header-group}th{color:#06396b;border-bottom:1px solid;padding:5px;text-align:left}td{padding:4px 5px}.num{text-align:right}.group td{font-weight:bold;padding-top:9px}td span{display:block;height:14px;border-bottom:1px solid}tr{break-inside:avoid}</style></head><body><div class="head"><div>DOKTER AC MOBIL</div><h1>Lembar Penghitungan Stok</h1><div>Per Tgl. ${dateLabel(selected.startDate)}</div></div><div class="meta">${escapeHtml(selected.orderNumber)} · ${escapeHtml(selected.warehouseName)} · ${escapeHtml(selected.assignedUserName)}</div><table><thead><tr><th>Kode</th><th>Nama Barang</th><th>Saldo</th><th>Satuan</th><th>Hitung #1</th><th>Hitung #2</th><th>Selisih</th></tr></thead><tbody>${body}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`);popup.document.close();};

 if(selected)return <div className="-m-4 min-h-[calc(100vh-80px)] bg-slate-100 sm:-m-6"><div className="flex flex-wrap items-center gap-2 border-b bg-white p-3"><button onClick={()=>setSelected(null)} className="rounded border p-2"><ArrowLeft className="h-5 w-5"/></button><div><h1 className="font-bold">{selected.orderNumber}</h1><p className="text-xs text-slate-500">{selected.result?.resultNumber||'Hasil belum dibuat'}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusTone[selected.status]}`}>{selected.status}</span><div className="ml-auto flex gap-2">{selected.result&&<button onClick={printSheet} className="flex items-center gap-2 rounded border border-blue-500 px-3 py-2 text-sm text-blue-700"><Printer className="h-4 w-4"/>Cetak</button>}{selected.status==='Menunggu Eksekusi'&&<button onClick={()=>void action('start')} disabled={loading} className="flex items-center gap-2 rounded bg-green-600 px-4 py-2 text-sm font-semibold text-white"><Play className="h-4 w-4"/>Buat Hasil</button>}{selected.status==='Menunggu Eksekusi'&&<button onClick={()=>void remove('order')} className="rounded border border-red-400 p-2 text-red-600"><Trash2 className="h-4 w-4"/></button>}</div></div>
 {message&&<div className="m-3 rounded border border-blue-200 bg-blue-50 px-4 py-2 text-sm text-blue-800">{message}</div>}<div className="grid gap-3 p-3 lg:grid-cols-[280px_1fr]"><aside className="h-fit rounded border bg-white p-4 text-sm"><h2 className="font-bold">Parameter Perintah</h2><dl className="mt-3 space-y-3"><Info label="Tanggal Mulai" value={dateLabel(selected.startDate)}/><Info label="Gudang" value={`${selected.warehouseCode} · ${selected.warehouseName}`}/><Info label="Cabang" value={selected.branchName}/><Info label="Dikerjakan Oleh" value={selected.assignedUserName}/><Info label="Penyesuaian" value={selected.result?.adjustmentNumber||'Belum ada'}/></dl>{selected.result&&<button onClick={()=>void remove('result')} className="mt-5 w-full rounded border border-red-300 px-3 py-2 text-red-700">Hapus Hasil Stok Opname</button>}</aside><main className="overflow-hidden rounded border bg-white"><div className="flex items-center justify-between gap-2 border-b bg-[#0c3262] px-4 py-3 text-white"><div><h2 className="font-bold">{selected.result?.resultNumber||'Menunggu Eksekusi'}</h2><p className="text-xs text-blue-100">{selected.rows?.length||0} barang</p></div>{selected.status==='Dalam Penghitungan'&&<div className="flex gap-2"><button onClick={()=>void action('save-result')} className="flex items-center gap-2 rounded bg-white px-3 py-2 text-sm font-semibold text-blue-800"><Save className="h-4 w-4"/>Simpan</button>{canPost&&<button onClick={()=>void action('post-result')} className="flex items-center gap-2 rounded bg-green-500 px-3 py-2 text-sm font-semibold"><Send className="h-4 w-4"/>Setujui & Posting</button>}</div>}</div>{!selected.result?<div className="py-24 text-center text-slate-400"><ClipboardCheck className="mx-auto h-12 w-12"/><p className="mt-3">Klik Buat Hasil pada Tanggal Mulai.</p></div>:<div className="max-h-[calc(100vh-240px)] overflow-auto"><table className="w-full min-w-[760px] text-sm"><thead className="sticky top-0 bg-slate-100"><tr><th className="px-3 py-2 text-left">Kode / Barang</th><th className="px-3 py-2 text-right">Saldo Sistem</th><th className="px-3 py-2 text-right">Hitung #1</th><th className="px-3 py-2 text-right">Hitung #2</th><th className="px-3 py-2 text-right">Final</th><th className="px-3 py-2 text-right">Selisih</th></tr></thead><tbody>{grouped.map(([cat,rows])=><GroupRows key={cat} category={cat} rows={rows} editable={selected.status==='Dalam Penghitungan'} onChange={updateCount}/>)}</tbody></table></div>}</main></div></div>;

 return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Stok Opname</h1><p className="text-sm text-slate-500">Perintah → Hasil Penghitungan → Penyesuaian Stok</p></div><button onClick={()=>setShowNew(true)} className="flex items-center gap-2 rounded bg-green-600 px-4 py-2 font-semibold text-white"><FilePlus2 className="h-5 w-5"/>Perintah Baru</button></div>{message&&<div className="rounded border border-blue-200 bg-blue-50 px-4 py-2 text-sm text-blue-800">{message}</div>}<div className="rounded border bg-white"><div className="relative border-b p-3"><Search className="absolute left-6 top-5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari nomor, gudang, petugas, atau status" className="w-full rounded border py-2 pl-10 pr-3 text-sm"/></div><div className="overflow-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-[#68849d] text-white"><tr><th className="px-4 py-3 text-left">Nomor</th><th className="px-4 py-3 text-left">Tanggal Mulai</th><th className="px-4 py-3 text-left">Gudang</th><th className="px-4 py-3 text-left">Petugas</th><th className="px-4 py-3 text-left">Status</th><th className="px-4 py-3">Aksi</th></tr></thead><tbody>{filtered.map(order=><tr key={order.id} className="border-b hover:bg-blue-50"><td className="px-4 py-3 font-mono font-semibold text-blue-700">{order.orderNumber}<div className="text-xs font-normal text-slate-400">{order.result?.resultNumber}</div></td><td className="px-4 py-3">{dateLabel(order.startDate)}</td><td className="px-4 py-3">{order.warehouseName}</td><td className="px-4 py-3">{order.assignedUserName}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${statusTone[order.status]}`}>{order.status}</span></td><td className="px-4 py-3 text-center"><button onClick={()=>void openDetail(order.id)} className="text-blue-700"><Eye className="h-5 w-5"/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="py-14 text-center text-slate-400">Belum ada Perintah Stok Opname.</div>}</div></div>
 {showNew&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/50 p-3"><div className="w-full max-w-2xl overflow-hidden rounded bg-white shadow-2xl"><header className="flex items-center justify-between bg-[#0c3262] px-5 py-4 text-white"><h2 className="text-xl font-semibold">Perintah Stok Opname</h2><button onClick={()=>setShowNew(false)}><X/></button></header><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="Tanggal Mulai"><input type="date" min={localDateKey()} value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></Field><Field label="Cabang"><select value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value,warehouseId:''})}><option value="">Pilih Cabang</option>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Gudang"><select value={form.warehouseId} onChange={e=>setForm({...form,warehouseId:e.target.value})}><option value="">Pilih Gudang</option>{warehouses.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></Field><Field label="Dikerjakan Oleh"><select value={form.assignedUserId} onChange={e=>setForm({...form,assignedUserId:e.target.value})}><option value="">Pilih Petugas</option>{users.map(x=><option key={x.id} value={x.id}>{x.name||x.username}</option>)}</select></Field><Field label="Kategori Barang"><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Semua Kategori</option>{data.itemCategories.filter(x=>x.isActive).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><label className="text-sm sm:col-span-2">Catatan<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="mt-1 w-full rounded border px-3 py-2" rows={2}/></label></div><footer className="flex justify-end border-t p-4"><button onClick={()=>void createOrder()} disabled={loading} className="rounded bg-blue-700 px-6 py-2 font-semibold text-white disabled:opacity-50">Simpan Perintah</button></footer></div></div>}
 </div>;
}

function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-slate-500">{label}</dt><dd>{value}</dd></div>}
function Field({label,children}:{label:string;children:React.ReactElement}){return <label className="text-sm">{label} *<span className="mt-1 block [&>*]:w-full [&>*]:rounded [&>*]:border [&>*]:px-3 [&>*]:py-2">{children}</span></label>}
function GroupRows({category,rows,editable,onChange}:{category:string;rows:CountRow[];editable:boolean;onChange:(id:number,key:'count1'|'count2',value:string)=>void}){return <><tr className="bg-slate-50"><td colSpan={6} className="px-3 py-2 font-bold">{category}</td></tr>{rows.map(row=>{const final=row.count2??row.count1,variance=final===null?null:final-row.systemQuantity;return <tr key={row.id} className="border-b"><td className="px-3 py-2"><b className="font-mono text-blue-700">{row.code}</b><div>{row.name}</div><span className="text-xs text-slate-400">{row.unit}</span></td><td className="px-3 py-2 text-right font-semibold">{row.systemQuantity}</td><td className="px-3 py-2 text-right">{editable?<input type="number" min="0" value={row.count1??''} onChange={e=>onChange(row.id,'count1',e.target.value)} className="w-24 rounded border px-2 py-1 text-right"/>:row.count1??'-'}</td><td className="px-3 py-2 text-right">{editable?<input type="number" min="0" value={row.count2??''} onChange={e=>onChange(row.id,'count2',e.target.value)} className="w-24 rounded border px-2 py-1 text-right"/>:row.count2??'-'}</td><td className="px-3 py-2 text-right font-semibold">{final??'-'}</td><td className={`px-3 py-2 text-right font-bold ${variance===null?'':variance<0?'text-red-600':variance>0?'text-green-600':'text-slate-500'}`}>{variance===null?'-':variance>0?`+${variance}`:variance}</td></tr>})}</>}
