import { useEffect,useMemo,useState } from 'react';
import { Check,Package,Plus,Search,X } from 'lucide-react';
import { api } from '../lib/apiClient';
import { useApp } from '../context/AppContext';
import { localDateKey } from '../lib/date';

type TransferItem={itemId:string;itemCode:string;itemName:string;categoryName:string;unit:string;qtySent:number;qtyReceived:number};
type Transfer={id:string;transferNumber:string;date:string;sourceWarehouseId:string;sourceWarehouseName:string;sourceBranchName:string;destinationWarehouseId:string;destinationWarehouseName:string;destinationBranchId:string;destinationBranchName:string;status:string;items:TransferItem[]};

export default function WarehouseTransfers(){
 const{data,currentBranchId,currentUser,refreshData}=useApp();const activeBranchId=(currentBranchId==='ALL'?currentUser?.branchId:currentBranchId)||'';
 const[process,setProcess]=useState<'Kirim Barang'|'Terima Barang'>('Kirim Barang');const[transfers,setTransfers]=useState<Transfer[]>([]);const[warehouseOptions,setWarehouseOptions]=useState<Array<{id:string;code:string;name:string;branchId:string;branchName:string;isDefault:boolean}>>([]);const[search,setSearch]=useState('');const[showPicker,setShowPicker]=useState(false);const[showTake,setShowTake]=useState(false);const[selectedTransfer,setSelectedTransfer]=useState<Transfer|null>(null);const[receiveQty,setReceiveQty]=useState<Record<string,number>>({});const[message,setMessage]=useState('');
 const[form,setForm]=useState({date:localDateKey(),sourceWarehouseId:'',destinationWarehouseId:'',sentById:currentUser?.id||'',deliveryMethod:'Diantar Langsung',notes:'',items:[] as Array<{itemId:string;itemCode:string;itemName:string;categoryName:string;unit:string;qty:number}>});
 const load=async()=>{const r=await api.get<{transfers:Transfer[];warehouses:typeof warehouseOptions}>('warehouse-transfers');setTransfers(r.data?.transfers||[]);setWarehouseOptions(r.data?.warehouses||[])};useEffect(()=>{load()},[]);
 const sourceWarehouses=data.warehouses.filter(w=>w.isActive&&!w.isSystem&&(currentBranchId==='ALL'||w.branchId===activeBranchId));const stock=(warehouseId:string,itemId:string)=>data.warehouseStocks.find(s=>s.warehouseId===warehouseId&&s.itemId===itemId)?.quantity||0;
 const candidates=useMemo(()=>{const q=search.toLowerCase();return data.items.filter(i=>i.type==='Persediaan'&&i.isActive&&(!q||i.code.toLowerCase().includes(q)||i.name.toLowerCase().includes(q))).slice(0,25)},[data.items,search]);
 const pending=transfers.filter(t=>['Dalam Perjalanan','Diterima Sebagian'].includes(t.status)&&t.destinationBranchId===activeBranchId);
 const addItem=(i:typeof data.items[number])=>{if(form.items.some(x=>x.itemId===i.id))return;setForm({...form,items:[...form.items,{itemId:i.id,itemCode:i.code,itemName:i.name,categoryName:i.categoryName,unit:i.unit,qty:1}]});setShowPicker(false);setSearch('')};
 const send=async(action:'draft'|'send')=>{if(!form.sourceWarehouseId||!form.destinationWarehouseId||!form.items.length)return alert('Lengkapi gudang dan rincian barang.');const sender=data.users.find(u=>u.id===form.sentById);const r=await api.create('warehouse-transfers',{...form,action,sentByName:sender?.name||currentUser?.name});if(!r.success)return alert(r.message||'Transfer gagal');setMessage(`${r.data?.transferNumber||'Transfer'} berhasil disimpan.`);setForm({...form,items:[],notes:''});await Promise.all([load(),refreshData()])};
 const chooseTransfer=(t:Transfer)=>{setSelectedTransfer(t);const qty:Record<string,number>={};t.items.forEach(i=>qty[i.itemId]=Math.max(0,i.qtySent-i.qtyReceived));setReceiveQty(qty);setShowTake(false)};
 const receive=async()=>{if(!selectedTransfer)return;const receiver=data.users.find(u=>u.id===(form.sentById||currentUser?.id));const items=selectedTransfer.items.filter(i=>(receiveQty[i.itemId]||0)>0).map(i=>({itemId:i.itemId,qtyReceived:receiveQty[i.itemId]}));const r=await api.update('warehouse-transfers',selectedTransfer.id,{action:'receive',receivedById:receiver?.id||currentUser?.id,receivedByName:receiver?.name||currentUser?.name,items});if(!r.success)return alert(r.message||'Penerimaan gagal');setMessage('Transfer berhasil diterima.');setSelectedTransfer(null);await Promise.all([load(),refreshData()])};
 const branchUsers=data.users.filter(u=>u.isActive&&(u.branchId===activeBranchId||u.branchIds?.includes(activeBranchId)||u.isOwner));
 return <div className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold">Transfer Gudang</h2><p className="text-sm text-gray-500">Pengiriman dan penerimaan barang antar gudang dalam satu modul.</p></div><span className="rounded-lg bg-blue-50 px-4 py-2 font-semibold text-blue-700">{data.branches.find(b=>b.id===activeBranchId)?.name||'Semua Cabang'}</span></div>{message&&<div className="rounded-lg bg-green-50 p-3 text-green-700">{message}</div>}
 <section className="rounded-xl border bg-white shadow-sm"><div className="grid gap-3 border-b p-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Proses"><select value={process} onChange={e=>{setProcess(e.target.value as any);setSelectedTransfer(null)}}><option>Kirim Barang</option><option>Terima Barang</option></select></Field>
 {process==='Kirim Barang'?<><Field label="Gudang Asal *"><select value={form.sourceWarehouseId} onChange={e=>setForm({...form,sourceWarehouseId:e.target.value,destinationWarehouseId:''})}><option value="">Pilih gudang</option>{sourceWarehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></Field><Field label="Gudang Tujuan *"><select value={form.destinationWarehouseId} onChange={e=>setForm({...form,destinationWarehouseId:e.target.value})}><option value="">Pilih tujuan</option>{warehouseOptions.filter(w=>w.id!==form.sourceWarehouseId).map(w=><option key={w.id} value={w.id}>{w.branchName} • {w.name}</option>)}</select></Field><Field label="Tanggal"><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field></>:<><Field label="Pengiriman Barang *"><button onClick={()=>setShowTake(true)} className="w-full rounded-lg border px-3 py-2 text-left text-blue-700">{selectedTransfer?.transferNumber||'Ambil dari Pengiriman...'}</button></Field><Field label="Gudang Penerima"><input readOnly value={selectedTransfer?.destinationWarehouseName||'-'}/></Field><Field label="Gudang Pengirim"><input readOnly value={selectedTransfer?.sourceWarehouseName||'-'}/></Field></>}</div>
 <div className="p-4"><div className="mb-3 flex items-center justify-between"><h3 className="flex items-center gap-2 font-semibold"><Package className="h-5 w-5 text-blue-600"/>Rincian Barang</h3>{process==='Kirim Barang'&&<button onClick={()=>setShowPicker(!showPicker)} className="flex items-center gap-1 rounded-lg bg-blue-600 px-3 py-2 text-sm text-white"><Plus className="h-4 w-4"/>Ambil Barang</button>}</div>
 {showPicker&&<div className="mb-3 rounded-lg border bg-gray-50 p-3"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400"/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari barang..." className="w-full rounded-lg border py-2 pl-9"/></div><div className="mt-2 max-h-52 overflow-auto">{candidates.map(i=><button key={i.id} onClick={()=>addItem(i)} className="flex w-full justify-between border-b bg-white p-2 text-left text-sm"><span>{i.code} • {i.name}</span><b>Stok {stock(form.sourceWarehouseId,i.id)}</b></button>)}</div></div>}
 <div className="min-h-72 overflow-x-auto rounded-lg border"><table className="w-full text-sm"><thead className="bg-slate-600 text-white"><tr><th className="p-3 text-left">Nama Barang</th><th>Kode</th><th>{process==='Terima Barang'?'Qty Kirim':'Kuantitas'}</th>{process==='Terima Barang'&&<><th>Sudah</th><th>Qty Diterima</th></>}<th>Satuan</th><th>Kategori</th><th></th></tr></thead><tbody>{process==='Kirim Barang'?form.items.map(i=><tr key={i.itemId} className="border-t"><td className="p-3">{i.itemName}</td><td>{i.itemCode}</td><td><input type="number" min="1" max={stock(form.sourceWarehouseId,i.itemId)} value={i.qty} onChange={e=>setForm({...form,items:form.items.map(x=>x.itemId===i.itemId?{...x,qty:Number(e.target.value)}:x)})} className="w-24 text-center"/></td><td>{i.unit}</td><td>{i.categoryName}</td><td><button onClick={()=>setForm({...form,items:form.items.filter(x=>x.itemId!==i.itemId)})}><X className="h-4 w-4 text-red-600"/></button></td></tr>):selectedTransfer?.items.map(i=><tr key={i.itemId} className="border-t"><td className="p-3">{i.itemName}</td><td>{i.itemCode}</td><td className="text-center">{i.qtySent}</td><td className="text-center">{i.qtyReceived}</td><td><input type="number" min="0" max={i.qtySent-i.qtyReceived} value={receiveQty[i.itemId]||0} onChange={e=>setReceiveQty({...receiveQty,[i.itemId]:Number(e.target.value)})} className="w-24 text-center"/></td><td>{i.unit}</td><td>{i.categoryName}</td><td/></tr>)}</tbody></table>{((process==='Kirim Barang'&&!form.items.length)||(process==='Terima Barang'&&!selectedTransfer))&&<p className="py-16 text-center text-gray-400">Belum ada data.</p>}</div>
 <div className="mt-3 grid gap-3 md:grid-cols-3"><Field label={process==='Kirim Barang'?'Dikirim Oleh':'Diterima Oleh'}><select value={form.sentById} onChange={e=>setForm({...form,sentById:e.target.value})}>{branchUsers.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Cara Pengiriman"><select value={form.deliveryMethod} onChange={e=>setForm({...form,deliveryMethod:e.target.value})}>{['Diantar Langsung','Grab','Gojek','Ekspedisi','Diambil Sendiri','Lainnya'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Keterangan (opsional)"><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div>
 <div className="mt-4 flex justify-end gap-2">{process==='Kirim Barang'?<button onClick={()=>send('send')} className="rounded-lg bg-blue-600 px-5 py-2 font-semibold text-white">Kirim Barang</button>:<button disabled={!selectedTransfer} onClick={receive} className="rounded-lg bg-green-600 px-5 py-2 font-semibold text-white disabled:opacity-40"><Check className="mr-1 inline h-4 w-4"/>Terima Barang</button>}</div></div></section>
 <section className="rounded-xl border bg-white"><h3 className="border-b p-4 font-semibold">Riwayat Transfer</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">Nomor</th><th>Tanggal</th><th>Dari</th><th>Tujuan</th><th>Status</th></tr></thead><tbody>{transfers.map(t=><tr className="border-t" key={t.id}><td className="p-3 font-mono font-semibold text-blue-700">{t.transferNumber}</td><td>{t.date}</td><td>{t.sourceBranchName} • {t.sourceWarehouseName}</td><td>{t.destinationBranchName} • {t.destinationWarehouseName}</td><td><span className="rounded-full bg-blue-50 px-2 py-1 text-blue-700">{t.status}</span></td></tr>)}</tbody></table></div></section>
 {showTake&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-3xl rounded-xl bg-white shadow-2xl"><div className="flex items-center justify-between rounded-t-xl bg-blue-900 p-4 text-white"><b>Salin dari Pengiriman Barang</b><button onClick={()=>setShowTake(false)}><X/></button></div><div className="p-4"><div className="max-h-96 overflow-auto rounded-lg border">{pending.length?pending.map(t=><button key={t.id} onClick={()=>chooseTransfer(t)} className="flex w-full justify-between border-b p-4 text-left hover:bg-blue-50"><span><b className="font-mono text-blue-700">{t.transferNumber}</b><small className="block text-gray-500">{t.date} • {t.sourceBranchName} → {t.destinationBranchName}</small></span><span>{t.items.reduce((s,i)=>s+i.qtySent-i.qtyReceived,0)} barang</span></button>):<p className="p-12 text-center text-gray-500">Tidak ada pengiriman yang menunggu diterima.</p>}</div></div></div></div>}</div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm"><span className="mb-1 block font-medium text-gray-700">{label}</span><span className="block [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:px-3 [&_input]:py-2 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:px-3 [&_select]:py-2">{children}</span></label>}
