import { useMemo,useState } from 'react';
import { Boxes,Plus,Warehouse as WarehouseIcon } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../lib/apiClient';

export default function Warehouses(){
 const{data,refreshData,currentBranchId,currentUser}=useApp();const[showNew,setShowNew]=useState(false);const[message,setMessage]=useState('');const[form,setForm]=useState({code:'',name:'',branchId:data.branches[0]?.id||''});
 const warehouses=useMemo(()=>data.warehouses.filter(w=>w.isActive&&(currentBranchId==='ALL'||w.branchId===currentBranchId)),[data.warehouses,currentBranchId]);const inventory=data.items.filter(i=>i.type==='Persediaan'&&i.isActive);const stock=(warehouseId:string,itemId:string)=>data.warehouseStocks.find(s=>s.warehouseId===warehouseId&&s.itemId===itemId)?.quantity||0;
 const save=async(e:React.FormEvent)=>{e.preventDefault();const r=await api.create('warehouses',{...form,isSellable:true,isActive:true});setMessage(r.success?'Gudang berhasil ditambahkan.':r.message||'Gagal menambah gudang');if(r.success){setShowNew(false);await refreshData()}};
 return <div className="space-y-5"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold">Gudang & Stok</h2><p className="text-gray-500">Saldo persediaan per gudang. Pengiriman barang dilakukan melalui menu Transfer Gudang.</p></div>{currentUser?.isOwner&&<button onClick={()=>setShowNew(!showNew)} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-white"><Plus className="h-4 w-4"/>Gudang Baru</button>}</div>
 {message&&<div className="rounded-lg bg-blue-50 p-3 text-blue-700">{message}</div>}{showNew&&<form onSubmit={save} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4"><input required placeholder="Kode gudang" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} className="rounded-lg border px-3 py-2"/><input required placeholder="Nama gudang" value={form.name} onChange={e=>setForm({...form,name:e.target.value.toUpperCase()})} className="rounded-lg border px-3 py-2"/><select required value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})} className="rounded-lg border px-3 py-2"><option value="">Pilih cabang</option>{data.branches.filter(b=>b.isActive).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button className="rounded-lg bg-blue-600 px-4 py-2 text-white">Simpan Gudang</button></form>}
 <div className="grid gap-4 lg:grid-cols-3">{warehouses.map(w=><div key={w.id} className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-lg bg-cyan-100 p-2 text-cyan-700"><WarehouseIcon className="h-5 w-5"/></span><div><b>{w.name}</b><p className="text-xs text-gray-500">{w.code} • {w.branchName}{w.isDefault?' • Utama':''}</p></div></div><div className="mt-4 max-h-64 space-y-2 overflow-auto">{inventory.map(i=>{const qty=stock(w.id,i.id);return qty!==0?<div key={i.id} className="flex justify-between border-b pb-1 text-sm"><span>{i.name}</span><b className={qty<0?'text-red-600':''}>{qty} {i.unit}</b></div>:null})}<p className="text-xs text-gray-400"><Boxes className="mr-1 inline h-3 w-3"/>Saldo barang tersimpan per gudang</p></div></div>)}</div></div>
}
