import { useEffect, useMemo, useState } from 'react';
import { Clock3, History, Laptop, LogOut, RefreshCw, Settings2, ShieldCheck } from 'lucide-react';
import { api } from '../lib/apiClient';
import { useApp } from '../context/AppContext';
import { localDateKey } from '../lib/date';

type Session = { sessionId:string;userId:string;name:string;username:string;branchName:string;createdAt:string;lastActivity:string;expiresAt:string;ipAddress:string;userAgent:string;status:'online'|'idle';isOwner:boolean };
type Rule = { userId:string;sessionHours:number;idleTimeoutMinutes:number;scheduleMode:'unrestricted'|'custom';schedule:Record<string,{enabled:boolean;start:string;end:string}>;singleDevice:boolean;autoLogout:boolean };
type Log = { id:string;username:string;eventType:string;ipAddress:string;notes:string;createdAt:string };
const days=[['1','Senin'],['2','Selasa'],['3','Rabu'],['4','Kamis'],['5','Jumat'],['6','Sabtu'],['7','Minggu']];
const defaultSchedule=Object.fromEntries(days.map(([id])=>[id,{enabled:id!=='7',start:id==='6'?'08:00':'07:30',end:id==='6'?'15:00':'17:00'}]));

export default function UserSessionsTab(){
  const {data}=useApp(); const [payload,setPayload]=useState<{sessions:Session[];rules:Rule[];logs:Log[]}>({sessions:[],rules:[],logs:[]});
  const [loading,setLoading]=useState(true); const [view,setView]=useState<'active'|'history'|'rules'>('active'); const [editing,setEditing]=useState<string|null>(null);
  const [rule,setRule]=useState<Omit<Rule,'userId'>>({sessionHours:8,idleTimeoutMinutes:30,scheduleMode:'unrestricted',schedule:defaultSchedule,singleDevice:false,autoLogout:true});
  const load=async()=>{setLoading(true);const r=await api.get('user-sessions');if(r.success&&r.data)setPayload(r.data);setLoading(false)};
  useEffect(()=>{load()},[]);
  const online=payload.sessions.filter(s=>s.status==='online').length;
  const todayLogs=payload.logs.filter(l=>l.createdAt?.slice(0,10)===localDateKey());
  const openRule=(userId:string)=>{const current=payload.rules.find(r=>r.userId===userId);setRule(current?{sessionHours:current.sessionHours,idleTimeoutMinutes:current.idleTimeoutMinutes??30,scheduleMode:current.scheduleMode,schedule:{...defaultSchedule,...current.schedule},singleDevice:current.singleDevice,autoLogout:current.autoLogout}:{sessionHours:8,idleTimeoutMinutes:30,scheduleMode:'unrestricted',schedule:defaultSchedule,singleDevice:false,autoLogout:true});setEditing(userId)};
  const saveRule=async(e:React.FormEvent)=>{e.preventDefault();if(!editing)return;const r=await api.update('user-sessions',`${editing}/rules`,rule);if(!r.success)return alert(r.message);setEditing(null);await load()};
  const revoke=async(s:Session)=>{if(!confirm(`Putuskan sesi ${s.name}?`))return;const r=await api.remove('user-sessions',s.sessionId);if(!r.success)alert(r.message);else await load()};
  const editableUsers=useMemo(()=>data.users.filter(u=>!u.isOwner),[data.users]);
  return <div className="space-y-4">
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="User Online" value={online} color="emerald"/><Stat label="Sesi Aktif" value={payload.sessions.length} color="blue"/><Stat label="Login Ditolak Hari Ini" value={todayLogs.filter(l=>l.eventType==='login_blocked'||l.eventType==='login_failed').length} color="red"/></div>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-lg bg-gray-100 p-1">{([['active','User Aktif',Laptop],['history','Riwayat Login',History],['rules','Aturan Login',Settings2]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setView(id)} className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm ${view===id?'bg-white font-semibold text-blue-700 shadow-sm':'text-gray-600'}`}><Icon className="h-4 w-4"/>{label}</button>)}</div><button onClick={load} className="rounded-lg border p-2 text-gray-600"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
    {view==='active'&&<div className="overflow-hidden rounded-xl border bg-white"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-100 text-left text-xs uppercase text-slate-600"><tr><th className="p-3">Pengguna</th><th>Cabang</th><th>Perangkat / IP</th><th>Login</th><th>Berakhir</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{payload.sessions.map(s=><tr key={s.sessionId} className="border-t"><td className="p-3 font-semibold">{s.name}{s.isOwner&&<span className="ml-2 rounded bg-amber-100 px-1.5 py-0.5 text-[10px] text-amber-700">OWNER</span>}<div className="text-xs font-normal text-gray-400">@{s.username}</div></td><td>{s.branchName}</td><td className="max-w-56 truncate" title={s.userAgent}>{deviceName(s.userAgent)}<div className="text-xs text-gray-400">{s.ipAddress||'-'}</div></td><td>{s.createdAt}</td><td>{s.expiresAt}</td><td><span className={`rounded-full px-2 py-1 text-xs ${s.status==='online'?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}>● {s.status==='online'?'Online':'Idle'}</span></td><td>{!s.isOwner?<button onClick={()=>revoke(s)} className="flex items-center gap-1 rounded border border-red-200 px-2 py-1 text-red-600"><LogOut className="h-3 w-3"/> Putuskan</button>:<ShieldCheck className="h-4 w-4 text-amber-500"/>}</td></tr>)}</tbody></table></div>{!payload.sessions.length&&!loading&&<p className="p-8 text-center text-gray-400">Tidak ada sesi aktif.</p>}</div>}
    {view==='history'&&<div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-100 text-left"><tr><th className="p-3">Waktu</th><th>User</th><th>Kejadian</th><th>IP</th><th>Keterangan</th></tr></thead><tbody>{payload.logs.map(l=><tr key={l.id} className="border-t"><td className="p-3">{l.createdAt}</td><td>{l.username}</td><td><EventBadge event={l.eventType}/></td><td>{l.ipAddress||'-'}</td><td>{l.notes}</td></tr>)}</tbody></table></div>}
    {view==='rules'&&<div className="space-y-2">{editableUsers.map(u=>{const r=payload.rules.find(x=>x.userId===u.id);return <div key={u.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-4"><div><p className="font-semibold">{u.name}</p><p className="text-xs text-gray-500">{u.branchName} · {r?.scheduleMode==='custom'?'Jadwal khusus':'Tidak dibatasi'} · Sesi {r?.sessionHours||8} jam</p></div><button onClick={()=>openRule(u.id)} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm text-blue-700"><Clock3 className="h-4 w-4"/> Atur Jam Login</button></div>})}<div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-700">Owner Utama tidak dibatasi dan sesinya tidak dapat diputus.</div></div>}
    {editing&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={saveRule} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-xl bg-white p-6"><h3 className="text-lg font-bold">Aturan Login — {data.users.find(u=>u.id===editing)?.name}</h3><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm">Durasi sesi<select value={rule.sessionHours} onChange={e=>setRule({...rule,sessionHours:Number(e.target.value)})} className="mt-1 w-full rounded-lg border px-3 py-2">{[1,4,8,12,24].map(h=><option key={h} value={h}>{h} jam</option>)}</select></label><label className="text-sm">Timeout tidak aktif<select value={rule.idleTimeoutMinutes} onChange={e=>setRule({...rule,idleTimeoutMinutes:Number(e.target.value)})} className="mt-1 w-full rounded-lg border px-3 py-2"><option value={0}>Tidak dibatasi</option><option value={15}>15 menit</option><option value={30}>30 menit</option><option value={60}>1 jam</option><option value={120}>2 jam</option></select></label><label className="text-sm">Jadwal login<select value={rule.scheduleMode} onChange={e=>setRule({...rule,scheduleMode:e.target.value as any})} className="mt-1 w-full rounded-lg border px-3 py-2"><option value="unrestricted">Tidak dibatasi</option><option value="custom">Jadwal khusus</option></select></label></div>{rule.scheduleMode==='custom'&&<div className="mt-4 space-y-2">{days.map(([id,name])=>{const d=rule.schedule[id]||defaultSchedule[id];return <div key={id} className="grid grid-cols-[90px_1fr_1fr] items-center gap-2 rounded-lg border p-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={d.enabled} onChange={e=>setRule({...rule,schedule:{...rule.schedule,[id]:{...d,enabled:e.target.checked}}})}/>{name}</label><input type="time" disabled={!d.enabled} value={d.start} onChange={e=>setRule({...rule,schedule:{...rule.schedule,[id]:{...d,start:e.target.value}}})} className="rounded border px-2 py-1"/><input type="time" disabled={!d.enabled} value={d.end} onChange={e=>setRule({...rule,schedule:{...rule.schedule,[id]:{...d,end:e.target.value}}})} className="rounded border px-2 py-1"/></div>})}</div>}<div className="mt-4 space-y-2"><label className="flex gap-2 text-sm"><input type="checkbox" checked={rule.singleDevice} onChange={e=>setRule({...rule,singleDevice:e.target.checked})}/> Batasi satu perangkat aktif</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={rule.autoLogout} onChange={e=>setRule({...rule,autoLogout:e.target.checked})}/> Logout otomatis saat jadwal berakhir</label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setEditing(null)} className="rounded-lg border px-4 py-2">Batal</button><button className="rounded-lg bg-blue-600 px-4 py-2 text-white">Simpan Aturan</button></div></form></div>}
  </div>
}
function Stat({label,value,color}:{label:string;value:number;color:string}){const colorClass=color==='emerald'?'text-emerald-600':color==='red'?'text-red-600':'text-blue-600';return <div className="rounded-xl border bg-white p-4"><p className="text-sm text-gray-500">{label}</p><p className={`text-2xl font-bold ${colorClass}`}>{value}</p></div>}
function deviceName(ua:string){if(!ua)return'-';const os=/Android/i.test(ua)?'Android':/iPhone|iPad/i.test(ua)?'iOS':/Windows/i.test(ua)?'Windows':'Perangkat';const browser=/Edg/i.test(ua)?'Edge':/Chrome/i.test(ua)?'Chrome':/Firefox/i.test(ua)?'Firefox':/Safari/i.test(ua)?'Safari':'Browser';return `${browser} · ${os}`}
function EventBadge({event}:{event:string}){const ok=event==='login_success';return <span className={`rounded px-2 py-1 text-xs ${ok?'bg-emerald-100 text-emerald-700':event==='logout'?'bg-gray-100 text-gray-600':'bg-red-100 text-red-700'}`}>{event.replace(/_/g,' ')}</span>}
